<?php

define('TLDS', [

'.com' => ['type' => 'original', 'info' => 'commercial'],
'.org' => ['type' => 'original', 'info' => 'organization'],
'.net' => ['type' => 'original', 'info' => 'network'],
'.int' => ['type' => 'original', 'info' => 'international organizations'],
'.arpa' => ['type' => 'original', 'info' => '"Address and Routing Parameter Area"'],
'.edu' => ['type' => 'usa', 'info' => 'education'],
'.gov' => ['type' => 'usa', 'info' => 'U.S. national and state government agencies'],
'.mil' => ['type' => 'usa', 'info' => 'U.S. military'],
'.ac' => ['type' => 'country', 'info' => 'Ascension Island'],
'.ad' => ['type' => 'country', 'info' => 'Andorra'],
'.ae' => ['type' => 'country', 'info' => 'United Arab Emirates'],
'.af' => ['type' => 'country', 'info' => 'Afghanistan'],
'.ag' => ['type' => 'country', 'info' => 'Antigua and Barbuda'],
'.ai' => ['type' => 'country', 'info' => 'Anguilla'],
'.al' => ['type' => 'country', 'info' => 'Albania'],
'.am' => ['type' => 'country', 'info' => 'Armenia'],
'.an' => ['type' => 'country', 'info' => 'Netherlands Antilles'],
'.ao' => ['type' => 'country', 'info' => 'Angola'],
'.aq' => ['type' => 'country', 'info' => 'Antarctica'],
'.ar' => ['type' => 'country', 'info' => 'Argentina'],
'.as' => ['type' => 'country', 'info' => 'American Samoa'],
'.at' => ['type' => 'country', 'info' => 'Austria'],
'.au' => ['type' => 'country', 'info' => 'Australia'],
'.aw' => ['type' => 'country', 'info' => 'Aruba'],
'.ax' => ['type' => 'country', 'info' => 'Åland'],
'.az' => ['type' => 'country', 'info' => 'Azerbaijan'],
'.ba' => ['type' => 'country', 'info' => 'Bosnia and Herzegovina'],
'.bb' => ['type' => 'country', 'info' => 'Barbados'],
'.bd' => ['type' => 'country', 'info' => 'Bangladesh'],
'.be' => ['type' => 'country', 'info' => 'Belgium'],
'.bf' => ['type' => 'country', 'info' => 'Burkina Faso'],
'.bg' => ['type' => 'country', 'info' => 'Bulgaria'],
'.bh' => ['type' => 'country', 'info' => 'Bahrain'],
'.bi' => ['type' => 'country', 'info' => 'Burundi'],
'.bj' => ['type' => 'country', 'info' => 'Benin'],
'.bl' => ['type' => 'country', 'info' => 'Saint Barthélemy'],
'.bm' => ['type' => 'country', 'info' => 'Bermuda'],
'.bn' => ['type' => 'country', 'info' => 'Brunei'],
'.bo' => ['type' => 'country', 'info' => 'Bolivia'],
'.bq' => ['type' => 'country', 'info' => 'Bonaire'],
'.br' => ['type' => 'country', 'info' => 'Brazil'],
'.bs' => ['type' => 'country', 'info' => 'Bahamas'],
'.bt' => ['type' => 'country', 'info' => 'Bhutan'],
'.bv' => ['type' => 'country', 'info' => 'Bouvet Island'],
'.bw' => ['type' => 'country', 'info' => 'Botswana'],
'.by' => ['type' => 'country', 'info' => 'Belarus'],
'.bz' => ['type' => 'country', 'info' => 'Belize'],
'.ca' => ['type' => 'country', 'info' => 'Canada'],
'.cc' => ['type' => 'country', 'info' => 'Cocos (Keeling) Islands'],
'.cd' => ['type' => 'country', 'info' => 'Democratic Republic of the Congo'],
'.cf' => ['type' => 'country', 'info' => 'Central African Republic'],
'.cg' => ['type' => 'country', 'info' => 'Republic of the Congo'],
'.ch' => ['type' => 'country', 'info' => 'Switzerland'],
'.ci' => ['type' => 'country', 'info' => 'Côte d\'Ivoire'],
'.ck' => ['type' => 'country', 'info' => 'Cook Islands'],
'.cl' => ['type' => 'country', 'info' => 'Chile'],
'.cm' => ['type' => 'country', 'info' => 'Cameroon'],
'.cn' => ['type' => 'country', 'info' => 'People\'s Republic of China'],
'.co' => ['type' => 'country', 'info' => 'Colombia'],
'.cr' => ['type' => 'country', 'info' => 'Costa Rica'],
'.cu' => ['type' => 'country', 'info' => 'Cuba'],
'.cv' => ['type' => 'country', 'info' => 'Cape Verde'],
'.cw' => ['type' => 'country', 'info' => 'Curaçao'],
'.cx' => ['type' => 'country', 'info' => 'Christmas Island'],
'.cy' => ['type' => 'country', 'info' => 'Cyprus'],
'.cz' => ['type' => 'country', 'info' => 'Czech Republic'],
'.de' => ['type' => 'country', 'info' => 'Germany'],
'.dj' => ['type' => 'country', 'info' => 'Djibouti'],
'.dk' => ['type' => 'country', 'info' => 'Denmark'],
'.dm' => ['type' => 'country', 'info' => 'Dominica'],
'.do' => ['type' => 'country', 'info' => 'Dominican Republic'],
'.dz' => ['type' => 'country', 'info' => 'Algeria'],
'.ec' => ['type' => 'country', 'info' => 'Ecuador'],
'.ee' => ['type' => 'country', 'info' => 'Estonia'],
'.eg' => ['type' => 'country', 'info' => 'Egypt'],
'.eh' => ['type' => 'country', 'info' => 'Western Sahara'],
'.er' => ['type' => 'country', 'info' => 'Eritrea'],
'.es' => ['type' => 'country', 'info' => 'Spain'],
'.et' => ['type' => 'country', 'info' => 'Ethiopia'],
'.eu' => ['type' => 'country', 'info' => 'European Union'],
'.fi' => ['type' => 'country', 'info' => 'Finland'],
'.fj' => ['type' => 'country', 'info' => 'Fiji'],
'.fk' => ['type' => 'country', 'info' => 'Falkland Islands'],
'.fm' => ['type' => 'country', 'info' => 'Federated States of Micronesia'],
'.fo' => ['type' => 'country', 'info' => 'Faroe Islands'],
'.fr' => ['type' => 'country', 'info' => 'France'],
'.ga' => ['type' => 'country', 'info' => 'Gabon'],
'.gb' => ['type' => 'country', 'info' => 'United Kingdom'],
'.gd' => ['type' => 'country', 'info' => 'Grenada'],
'.ge' => ['type' => 'country', 'info' => 'Georgia'],
'.gf' => ['type' => 'country', 'info' => 'French Guiana'],
'.gg' => ['type' => 'country', 'info' => 'Guernsey'],
'.gh' => ['type' => 'country', 'info' => 'Ghana'],
'.gi' => ['type' => 'country', 'info' => 'Gibraltar'],
'.gl' => ['type' => 'country', 'info' => 'Greenland'],
'.gm' => ['type' => 'country', 'info' => 'The Gambia'],
'.gn' => ['type' => 'country', 'info' => 'Guinea'],
'.gp' => ['type' => 'country', 'info' => 'Guadeloupe'],
'.gq' => ['type' => 'country', 'info' => 'Equatorial Guinea'],
'.gr' => ['type' => 'country', 'info' => 'Greece'],
'.gs' => ['type' => 'country', 'info' => 'South Georgia and the South Sandwich Islands'],
'.gt' => ['type' => 'country', 'info' => 'Guatemala'],
'.gu' => ['type' => 'country', 'info' => 'Guam'],
'.gw' => ['type' => 'country', 'info' => 'Guinea-Bissau'],
'.gy' => ['type' => 'country', 'info' => 'Guyana'],
'.hk' => ['type' => 'country', 'info' => 'Hong Kong'],
'.hm' => ['type' => 'country', 'info' => 'Heard Island and McDonald Islands'],
'.hn' => ['type' => 'country', 'info' => 'Honduras'],
'.hr' => ['type' => 'country', 'info' => 'Croatia'],
'.ht' => ['type' => 'country', 'info' => 'Haiti'],
'.hu' => ['type' => 'country', 'info' => 'Hungary'],
'.id' => ['type' => 'country', 'info' => 'Indonesia'],
'.ie' => ['type' => 'country', 'info' => 'Ireland'],
'.il' => ['type' => 'country', 'info' => 'Israel'],
'.im' => ['type' => 'country', 'info' => 'Isle of Man'],
'.in' => ['type' => 'country', 'info' => 'India'],
'.io' => ['type' => 'country', 'info' => 'British Indian Ocean Territory'],
'.iq' => ['type' => 'country', 'info' => 'Iraq'],
'.ir' => ['type' => 'country', 'info' => 'Iran'],
'.is' => ['type' => 'country', 'info' => 'Iceland'],
'.it' => ['type' => 'country', 'info' => 'Italy'],
'.je' => ['type' => 'country', 'info' => 'Jersey'],
'.jm' => ['type' => 'country', 'info' => 'Jamaica'],
'.jo' => ['type' => 'country', 'info' => 'Jordan'],
'.jp' => ['type' => 'country', 'info' => 'Japan'],
'.ke' => ['type' => 'country', 'info' => 'Kenya'],
'.kg' => ['type' => 'country', 'info' => 'Kyrgyzstan'],
'.kh' => ['type' => 'country', 'info' => 'Cambodia'],
'.ki' => ['type' => 'country', 'info' => 'Kiribati'],
'.km' => ['type' => 'country', 'info' => 'Comoros'],
'.kn' => ['type' => 'country', 'info' => 'Saint Kitts and Nevis'],
'.kp' => ['type' => 'country', 'info' => 'North Korea'],
'.kr' => ['type' => 'country', 'info' => 'South Korea'],
'.kw' => ['type' => 'country', 'info' => 'Kuwait'],
'.ky' => ['type' => 'country', 'info' => 'Cayman Islands'],
'.kz' => ['type' => 'country', 'info' => 'Kazakhstan'],
'.la' => ['type' => 'country', 'info' => 'Laos'],
'.lb' => ['type' => 'country', 'info' => 'Lebanon'],
'.lc' => ['type' => 'country', 'info' => 'Saint Lucia'],
'.li' => ['type' => 'country', 'info' => 'Liechtenstein'],
'.lk' => ['type' => 'country', 'info' => 'Sri Lanka'],
'.lr' => ['type' => 'country', 'info' => 'Liberia'],
'.ls' => ['type' => 'country', 'info' => 'Lesotho'],
'.lt' => ['type' => 'country', 'info' => 'Lithuania'],
'.lu' => ['type' => 'country', 'info' => 'Luxembourg'],
'.lv' => ['type' => 'country', 'info' => 'Latvia'],
'.ly' => ['type' => 'country', 'info' => 'Libya'],
'.ma' => ['type' => 'country', 'info' => 'Morocco'],
'.mc' => ['type' => 'country', 'info' => 'Monaco'],
'.md' => ['type' => 'country', 'info' => 'Moldova'],
'.me' => ['type' => 'country', 'info' => 'Montenegro'],
'.mf' => ['type' => 'country', 'info' => 'Collectivity of Saint Martin'],
'.mg' => ['type' => 'country', 'info' => 'Madagascar'],
'.mh' => ['type' => 'country', 'info' => 'Marshall Islands'],
'.mk' => ['type' => 'country', 'info' => 'Macedonia'],
'.ml' => ['type' => 'country', 'info' => 'Mali'],
'.mm' => ['type' => 'country', 'info' => 'Myanmar'],
'.mn' => ['type' => 'country', 'info' => 'Mongolia'],
'.mo' => ['type' => 'country', 'info' => 'Macau'],
'.mp' => ['type' => 'country', 'info' => 'Northern Mariana Islands'],
'.mq' => ['type' => 'country', 'info' => 'Martinique'],
'.mr' => ['type' => 'country', 'info' => 'Mauritania'],
'.ms' => ['type' => 'country', 'info' => 'Montserrat'],
'.mt' => ['type' => 'country', 'info' => 'Malta'],
'.mu' => ['type' => 'country', 'info' => 'Mauritius'],
'.mv' => ['type' => 'country', 'info' => 'Maldives'],
'.mw' => ['type' => 'country', 'info' => 'Malawi'],
'.mx' => ['type' => 'country', 'info' => 'Mexico'],
'.my' => ['type' => 'country', 'info' => 'Malaysia'],
'.mz' => ['type' => 'country', 'info' => 'Mozambique'],
'.na' => ['type' => 'country', 'info' => 'Namibia'],
'.nc' => ['type' => 'country', 'info' => 'New Caledonia'],
'.ne' => ['type' => 'country', 'info' => 'Niger'],
'.nf' => ['type' => 'country', 'info' => 'Norfolk Island'],
'.ng' => ['type' => 'country', 'info' => 'Nigeria'],
'.ni' => ['type' => 'country', 'info' => 'Nicaragua'],
'.nl' => ['type' => 'country', 'info' => 'Netherlands'],
'.no' => ['type' => 'country', 'info' => 'Norway'],
'.np' => ['type' => 'country', 'info' => 'Nepal'],
'.nr' => ['type' => 'country', 'info' => 'Nauru'],
'.nu' => ['type' => 'country', 'info' => 'Niue'],
'.nz' => ['type' => 'country', 'info' => 'New Zealand'],
'.om' => ['type' => 'country', 'info' => 'Oman'],
'.pa' => ['type' => 'country', 'info' => 'Panama'],
'.pe' => ['type' => 'country', 'info' => 'Peru'],
'.pf' => ['type' => 'country', 'info' => 'French Polynesia'],
'.pg' => ['type' => 'country', 'info' => 'Papua New Guinea'],
'.ph' => ['type' => 'country', 'info' => 'Philippines'],
'.pk' => ['type' => 'country', 'info' => 'Pakistan'],
'.pl' => ['type' => 'country', 'info' => 'Poland'],
'.pm' => ['type' => 'country', 'info' => 'Saint-Pierre and Miquelon'],
'.pn' => ['type' => 'country', 'info' => 'Pitcairn Islands'],
'.pr' => ['type' => 'country', 'info' => 'Puerto Rico'],
'.ps' => ['type' => 'country', 'info' => 'Palestine'],
'.pt' => ['type' => 'country', 'info' => 'Portugal'],
'.pw' => ['type' => 'country', 'info' => 'Palau'],
'.py' => ['type' => 'country', 'info' => 'Paraguay'],
'.qa' => ['type' => 'country', 'info' => 'Qatar'],
'.re' => ['type' => 'country', 'info' => 'Réunion'],
'.ro' => ['type' => 'country', 'info' => 'Romania'],
'.rs' => ['type' => 'country', 'info' => 'Serbia'],
'.ru' => ['type' => 'country', 'info' => 'Russia'],
'.rw' => ['type' => 'country', 'info' => 'Rwanda'],
'.sa' => ['type' => 'country', 'info' => 'Saudi Arabia'],
'.sb' => ['type' => 'country', 'info' => 'Solomon Islands'],
'.sc' => ['type' => 'country', 'info' => 'Seychelles'],
'.sd' => ['type' => 'country', 'info' => 'Sudan'],
'.se' => ['type' => 'country', 'info' => 'Sweden'],
'.sg' => ['type' => 'country', 'info' => 'Singapore'],
'.sh' => ['type' => 'country', 'info' => 'Saint Helena'],
'.si' => ['type' => 'country', 'info' => 'Slovenia'],
'.sj' => ['type' => 'country', 'info' => 'Svalbard and Jan Mayen Islands'],
'.sk' => ['type' => 'country', 'info' => 'Slovakia'],
'.sl' => ['type' => 'country', 'info' => 'Sierra Leone'],
'.sm' => ['type' => 'country', 'info' => 'San Marino'],
'.sn' => ['type' => 'country', 'info' => 'Senegal'],
'.so' => ['type' => 'country', 'info' => 'Somalia'],
'.sr' => ['type' => 'country', 'info' => 'Suriname'],
'.ss' => ['type' => 'country', 'info' => 'South Sudan'],
'.st' => ['type' => 'country', 'info' => 'São Tomé and Príncipe'],
'.su' => ['type' => 'country', 'info' => 'Soviet Union'],
'.sv' => ['type' => 'country', 'info' => 'El Salvador'],
'.sx' => ['type' => 'country', 'info' => 'Sint Maarten'],
'.sy' => ['type' => 'country', 'info' => 'Syria'],
'.sz' => ['type' => 'country', 'info' => 'Swaziland'],
'.tc' => ['type' => 'country', 'info' => 'Turks and Caicos Islands'],
'.td' => ['type' => 'country', 'info' => 'Chad'],
'.tf' => ['type' => 'country', 'info' => 'French Southern and Antarctic Lands'],
'.tg' => ['type' => 'country', 'info' => 'Togo'],
'.th' => ['type' => 'country', 'info' => 'Thailand'],
'.tj' => ['type' => 'country', 'info' => 'Tajikistan'],
'.tk' => ['type' => 'country', 'info' => 'Tokelau'],
'.tl' => ['type' => 'country', 'info' => 'East Timor'],
'.tm' => ['type' => 'country', 'info' => 'Turkmenistan'],
'.tn' => ['type' => 'country', 'info' => 'Tunisia'],
'.to' => ['type' => 'country', 'info' => 'Tonga'],
'.tp' => ['type' => 'country', 'info' => 'East Timor'],
'.tr' => ['type' => 'country', 'info' => 'Turkey'],
'.tt' => ['type' => 'country', 'info' => 'Trinidad and Tobago'],
'.tv' => ['type' => 'country', 'info' => 'Tuvalu'],
'.tw' => ['type' => 'country', 'info' => 'Taiwan'],
'.tz' => ['type' => 'country', 'info' => 'Tanzania'],
'.ua' => ['type' => 'country', 'info' => 'Ukraine'],
'.ug' => ['type' => 'country', 'info' => 'Uganda'],
'.uk' => ['type' => 'country', 'info' => 'United Kingdom'],
'.um' => ['type' => 'country', 'info' => 'United States Minor Outlying Islands'],
'.us' => ['type' => 'country', 'info' => 'United States of America'],
'.uy' => ['type' => 'country', 'info' => 'Uruguay'],
'.uz' => ['type' => 'country', 'info' => 'Uzbekistan'],
'.va' => ['type' => 'country', 'info' => 'Vatican City'],
'.vc' => ['type' => 'country', 'info' => 'Saint Vincent and the Grenadines'],
'.ve' => ['type' => 'country', 'info' => 'Venezuela'],
'.vg' => ['type' => 'country', 'info' => 'British Virgin Islands'],
'.vi' => ['type' => 'country', 'info' => 'United States Virgin Islands'],
'.vn' => ['type' => 'country', 'info' => 'Vietnam'],
'.vu' => ['type' => 'country', 'info' => 'Vanuatu'],
'.wf' => ['type' => 'country', 'info' => 'Wallis and Futuna'],
'.ws' => ['type' => 'country', 'info' => 'Samoa'],
'.ye' => ['type' => 'country', 'info' => 'Yemen'],
'.yt' => ['type' => 'country', 'info' => 'Mayotte'],
'.za' => ['type' => 'country', 'info' => 'South Africa'],
'.zm' => ['type' => 'country', 'info' => 'Zambia'],
'.zw' => ['type' => 'country', 'info' => 'Zimbabwe'],

]);

define('TLDS_CUSTOM', [

'.academy' => ['type' => 'topic', 'info' => 'academic institutes'],
'.accountant' => ['type' => 'topic', 'info' => 'accountants and accounting firms'],
'.accountants' => ['type' => 'topic', 'info' => 'accountants and accounting firms'],
'.active' => ['type' => 'topic', 'info' => 'general'],
'.actor' => ['type' => 'topic', 'info' => 'actors'],
'.ads' => ['type' => 'topic', 'info' => ''],
'.adult' => ['type' => 'topic', 'info' => 'adult entertainment (pornography)'],
'.aero' => ['type' => 'topic', 'info' => 'air-transport industry'],
'.agency' => ['type' => 'topic', 'info' => 'business associations'],
'.airforce' => ['type' => 'topic', 'info' => 'defense contractors'],
'.analytics' => ['type' => 'topic', 'info' => ''],
'.apartments' => ['type' => 'topic', 'info' => 'apartments'],
'.app' => ['type' => 'topic', 'info' => 'Apps'],
'.archi' => ['type' => 'topic', 'info' => 'architects and architect firms'],
'.army' => ['type' => 'topic', 'info' => 'defense contractors'],
'.art' => ['type' => 'topic', 'info' => 'artists, museums, art galleries, dealers, service providers and contractors'],
'.associates' => ['type' => 'topic', 'info' => 'business associations'],
'.attorney' => ['type' => 'topic', 'info' => 'attorneys and legal organizations'],
'.auction' => ['type' => 'topic', 'info' => ''],
'.audible' => ['type' => 'topic', 'info' => ''],
'.audio' => ['type' => 'topic', 'info' => 'stereo/sound systems, music'],
'.author' => ['type' => 'topic', 'info' => ''],
'.auto' => ['type' => 'topic', 'info' => ''],
'.autos' => ['type' => 'topic', 'info' => ''],
'.aws' => ['type' => 'topic', 'info' => ''],
'.baby' => ['type' => 'topic', 'info' => ''],
'.band' => ['type' => 'topic', 'info' => ''],
'.bank' => ['type' => 'topic', 'info' => 'banks'],
'.bar' => ['type' => 'topic', 'info' => 'Bars and related industry'],
'.barefoot' => ['type' => 'topic', 'info' => ''],
'.bargains' => ['type' => 'topic', 'info' => 'coupons and online sellers'],
'.baseball' => ['type' => 'topic', 'info' => ''],
'.basketball' => ['type' => 'topic', 'info' => ''],
'.beauty' => ['type' => 'topic', 'info' => ''],
'.beer' => ['type' => 'topic', 'info' => 'breweries and beer aficionados'],
'.best' => ['type' => 'topic', 'info' => ''],
'.bestbuy' => ['type' => 'topic', 'info' => ''],
'.bet' => ['type' => 'topic', 'info' => ''],
'.bible' => ['type' => 'topic', 'info' => ''],
'.bid' => ['type' => 'topic', 'info' => 'auctions'],
'.bike' => ['type' => 'topic', 'info' => 'bicycles'],
'.bingo' => ['type' => 'topic', 'info' => 'bingo'],
'.bio' => ['type' => 'topic', 'info' => 'biodiversity, biographies'],
'.biz' => ['type' => 'topic', 'info' => 'business'],
'.black' => ['type' => 'topic', 'info' => 'those who like the color black'],
'.blackfriday' => ['type' => 'topic', 'info' => 'Black Friday, retail'],
'.blockbuster' => ['type' => 'topic', 'info' => ''],
'.blog' => ['type' => 'topic', 'info' => 'Blogs'],
'.blue' => ['type' => 'topic', 'info' => 'those who like the color blue'],
'.boo' => ['type' => 'topic', 'info' => '-'],
'.book' => ['type' => 'topic', 'info' => ''],
'.boots' => ['type' => 'topic', 'info' => ''],
'.bot' => ['type' => 'topic', 'info' => ''],
'.boutique' => ['type' => 'topic', 'info' => 'specialized businesses'],
'.box' => ['type' => 'topic', 'info' => 'individuals and businesses, in order to promote personal cloud storage'],
'.broadway' => ['type' => 'topic', 'info' => ''],
'.broker' => ['type' => 'topic', 'info' => ''],
'.build' => ['type' => 'topic', 'info' => 'construction industry'],
'.builders' => ['type' => 'topic', 'info' => 'construction workers'],
'.business' => ['type' => 'topic', 'info' => 'businesses'],
'.buy' => ['type' => 'topic', 'info' => ''],
'.buzz' => ['type' => 'topic', 'info' => 'marketing and social networking'],
'.cab' => ['type' => 'topic', 'info' => 'cabs and taxi companies'],
'.cafe' => ['type' => 'topic', 'info' => 'coffee industry'],
'.call' => ['type' => 'topic', 'info' => ''],
'.cam' => ['type' => 'topic', 'info' => 'entertainment'],
'.camera' => ['type' => 'topic', 'info' => 'camera-related businesses'],
'.camp' => ['type' => 'topic', 'info' => 'camps and camping'],
'.cancerresearch' => ['type' => 'topic', 'info' => 'Organizations, research institutes and individuals interested in ending cancer through research'],
'.capital' => ['type' => 'topic', 'info' => 'financial firms'],
'.car' => ['type' => 'topic', 'info' => ''],
'.cards' => ['type' => 'topic', 'info' => 'general'],
'.care' => ['type' => 'topic', 'info' => 'healthcare industry'],
'.career' => ['type' => 'topic', 'info' => ''],
'.careers' => ['type' => 'topic', 'info' => 'Employment'],
'.cars' => ['type' => 'topic', 'info' => 'Automotive'],
'.case' => ['type' => 'topic', 'info' => ''],
'.cash' => ['type' => 'topic', 'info' => 'financial'],
'.casino' => ['type' => 'topic', 'info' => 'casinos'],
'.catering' => ['type' => 'topic', 'info' => 'Food service'],
'.catholic' => ['type' => 'topic', 'info' => ''],
'.center' => ['type' => 'topic', 'info' => 'general'],
'.cern' => ['type' => 'topic', 'info' => 'CERN'],
'.ceo' => ['type' => 'topic', 'info' => 'CEOs'],
'.cfd' => ['type' => 'topic', 'info' => ''],
'.channel' => ['type' => 'topic', 'info' => ''],
'.chat' => ['type' => 'topic', 'info' => 'online chat'],
'.cheap' => ['type' => 'topic', 'info' => 'Resellers'],
'.christmas' => ['type' => 'topic', 'info' => 'Christmas'],
'.church' => ['type' => 'topic', 'info' => 'churches'],
'.cipriani' => ['type' => 'topic', 'info' => ''],
'.circle' => ['type' => 'topic', 'info' => ''],
'.city' => ['type' => 'topic', 'info' => 'general'],
'.claims' => ['type' => 'topic', 'info' => 'retail, auctions'],
'.cleaning' => ['type' => 'topic', 'info' => 'Cleaning services'],
'.click' => ['type' => 'topic', 'info' => ''],
'.clinic' => ['type' => 'topic', 'info' => 'healthcare clinics'],
'.clothing' => ['type' => 'topic', 'info' => 'Apparel'],
'.cloud' => ['type' => 'topic', 'info' => ''],
'.club' => ['type' => 'topic', 'info' => 'groups, organizations, assemblies, communities, general'],
'.coach' => ['type' => 'topic', 'info' => 'travel (flights and motor coaches)'],
'.codes' => ['type' => 'topic', 'info' => 'computer and/or encryption code enthusiasts'],
'.coffee' => ['type' => 'topic', 'info' => 'cafés and coffee aficionados'],
'.college' => ['type' => 'topic', 'info' => 'Educational'],
'.community' => ['type' => 'topic', 'info' => 'social groups, neighborhoods'],
'.company' => ['type' => 'topic', 'info' => 'business associations'],
'.compare' => ['type' => 'topic', 'info' => ''],
'.computer' => ['type' => 'topic', 'info' => 'Technology'],
'.condos' => ['type' => 'topic', 'info' => 'Real estate'],
'.construction' => ['type' => 'topic', 'info' => 'Construction industry'],
'.consulting' => ['type' => 'topic', 'info' => 'hired advisors'],
'.contact' => ['type' => 'topic', 'info' => ''],
'.contractors' => ['type' => 'topic', 'info' => 'Remodeling and independent businesses'],
'.cooking' => ['type' => 'topic', 'info' => 'sharing recipes'],
'.cool' => ['type' => 'topic', 'info' => 'General interests'],
'.coop' => ['type' => 'topic', 'info' => 'cooperatives'],
'.country' => ['type' => 'topic', 'info' => 'general'],
'.coupon' => ['type' => 'topic', 'info' => ''],
'.coupons' => ['type' => 'topic', 'info' => 'coupons'],
'.courses' => ['type' => 'topic', 'info' => ''],
'.credit' => ['type' => 'topic', 'info' => 'Financial institutions'],
'.creditcard' => ['type' => 'topic', 'info' => 'Financial institutions'],
'.cruise' => ['type' => 'topic', 'info' => ''],
'.cricket' => ['type' => 'topic', 'info' => 'cricket'],
'.cruises' => ['type' => 'topic', 'info' => 'cruise businesses and travel'],
'.dad' => ['type' => 'topic', 'info' => 'families'],
'.dance' => ['type' => 'topic', 'info' => 'Dance studios and companies'],
'.data' => ['type' => 'topic', 'info' => ''],
'.date' => ['type' => 'topic', 'info' => 'online dating'],
'.dating' => ['type' => 'topic', 'info' => 'online dating'],
'.day' => ['type' => 'topic', 'info' => 'general'],
'.deal' => ['type' => 'topic', 'info' => ''],
'.deals' => ['type' => 'topic', 'info' => 'online shopping and couponing'],
'.degree' => ['type' => 'topic', 'info' => 'general'],
'.delivery' => ['type' => 'topic', 'info' => 'general'],
'.democrat' => ['type' => 'topic', 'info' => 'Democratic Party politics'],
'.dental' => ['type' => 'topic', 'info' => 'dentists'],
'.dentist' => ['type' => 'topic', 'info' => 'dentists'],
'.design' => ['type' => 'topic', 'info' => 'graphic art and fashion'],
'.dev' => ['type' => 'topic', 'info' => 'development'],
'.diamonds' => ['type' => 'topic', 'info' => 'diamond and jewelry industry'],
'.diet' => ['type' => 'topic', 'info' => ''],
'.digital' => ['type' => 'topic', 'info' => 'general'],
'.direct' => ['type' => 'topic', 'info' => 'general'],
'.directory' => ['type' => 'topic', 'info' => 'general directory'],
'.discount' => ['type' => 'topic', 'info' => 'general'],
'.diy' => ['type' => 'topic', 'info' => ''],
'.docs' => ['type' => 'topic', 'info' => ''],
'.doctor' => ['type' => 'topic', 'info' => ''],
'.dog' => ['type' => 'topic', 'info' => 'dog stores and owners'],
'.domains' => ['type' => 'topic', 'info' => 'domain registries'],
'.dot' => ['type' => 'topic', 'info' => ''],
'.download' => ['type' => 'topic', 'info' => 'technology'],
'.drive' => ['type' => 'topic', 'info' => ''],
'.duck' => ['type' => 'topic', 'info' => ''],
'.earth' => ['type' => 'topic', 'info' => ''],
'.eat' => ['type' => 'topic', 'info' => 'restaurants and foodies'],
'.eco' => ['type' => 'topic', 'info' => 'Sustainability minded companies, non-profits and professionals.'],
'.education' => ['type' => 'topic', 'info' => 'educational institutes'],
'.email' => ['type' => 'topic', 'info' => 'email'],
'.energy' => ['type' => 'topic', 'info' => 'energy industry and marketing'],
'.engineer' => ['type' => 'topic', 'info' => 'engineers and engineering firms'],
'.engineering' => ['type' => 'topic', 'info' => 'engineering firms'],
'.enterprises' => ['type' => 'topic', 'info' => 'business associations'],
'.equipment' => ['type' => 'topic', 'info' => 'equipment-related businesses'],
'.esq' => ['type' => 'topic', 'info' => 'lawyers, law firms, legal professionals'],
'.estate' => ['type' => 'topic', 'info' => 'real estate businesses'],
'.events' => ['type' => 'topic', 'info' => 'happenings'],
'.exchange' => ['type' => 'topic', 'info' => 'generic trade'],
'.expert' => ['type' => 'topic', 'info' => 'generic expertise'],
'.exposed' => ['type' => 'topic', 'info' => 'general interest'],
'.express' => ['type' => 'topic', 'info' => 'shipping'],
'.fail' => ['type' => 'topic', 'info' => 'general'],
'.faith' => ['type' => 'topic', 'info' => 'religion and churches'],
'.family' => ['type' => 'topic', 'info' => 'families'],
'.fan' => ['type' => 'topic', 'info' => ''],
'.fans' => ['type' => 'topic', 'info' => 'general'],
'.farm' => ['type' => 'topic', 'info' => 'farms and agriculture'],
'.fashion' => ['type' => 'topic', 'info' => 'clothing industry'],
'.fast' => ['type' => 'topic', 'info' => ''],
'.feedback' => ['type' => 'topic', 'info' => ''],
'.film' => ['type' => 'topic', 'info' => ''],
'.final' => ['type' => 'topic', 'info' => ''],
'.finance' => ['type' => 'topic', 'info' => 'financial'],
'.financial' => ['type' => 'topic', 'info' => 'financial'],
'.fire' => ['type' => 'topic', 'info' => ''],
'.fish' => ['type' => 'topic', 'info' => 'fishing businesses, sports, and interests'],
'.fishing' => ['type' => 'topic', 'info' => 'fishing businesses, sports, and interests'],
'.fit' => ['type' => 'topic', 'info' => 'Fitness and exercise'],
'.fitness' => ['type' => 'topic', 'info' => 'Fitness and exercise'],
'.flights' => ['type' => 'topic', 'info' => 'airline businesses and travel'],
'.florist' => ['type' => 'topic', 'info' => 'florists'],
'.flowers' => ['type' => 'topic', 'info' => 'florists and gardens'],
'.fly' => ['type' => 'topic', 'info' => 'travel'],
'.foo' => ['type' => 'topic', 'info' => 'web development'],
'.food' => ['type' => 'topic', 'info' => ''],
'.foodnetwork' => ['type' => 'topic', 'info' => ''],
'.football' => ['type' => 'topic', 'info' => 'soccer and American football'],
'.forsale' => ['type' => 'topic', 'info' => 'online retail'],
'.forum' => ['type' => 'topic', 'info' => ''],
'.foundation' => ['type' => 'topic', 'info' => 'charitable organizations'],
'.free' => ['type' => 'topic', 'info' => ''],
'.frontdoor' => ['type' => 'topic', 'info' => ''],
'.fun' => ['type' => 'topic', 'info' => ''],
'.fund' => ['type' => 'topic', 'info' => 'financial'],
'.furniture' => ['type' => 'topic', 'info' => 'furniture businesses'],
'.fyi' => ['type' => 'topic', 'info' => '"for your information"'],
'.gallery' => ['type' => 'topic', 'info' => 'photo and art galleries'],
'.game' => ['type' => 'topic', 'info' => ''],
'.games' => ['type' => 'topic', 'info' => ''],
'.garden' => ['type' => 'topic', 'info' => 'gardening'],
'.gdn' => ['type' => 'topic', 'info' => 'none, anyone'],
'.gift' => ['type' => 'topic', 'info' => 'gift-giving'],
'.gifts' => ['type' => 'topic', 'info' => 'gift-giving'],
'.gives' => ['type' => 'topic', 'info' => 'charities and gift-giving'],
'.glass' => ['type' => 'topic', 'info' => 'window sales and repairs'],
'.global' => ['type' => 'topic', 'info' => 'general'],
'.gold' => ['type' => 'topic', 'info' => 'gold and luxury'],
'.golf' => ['type' => 'topic', 'info' => 'golf'],
'.gop' => ['type' => 'topic', 'info' => 'Republican Party politics'],
'.graphics' => ['type' => 'topic', 'info' => 'graphics'],
'.green' => ['type' => 'topic', 'info' => 'the environmentally-focused'],
'.gripe' => ['type' => 'topic', 'info' => 'opinion sites'],
'.grocery' => ['type' => 'topic', 'info' => ''],
'.group' => ['type' => 'topic', 'info' => ''],
'.guide' => ['type' => 'topic', 'info' => 'help sites'],
'.guitars' => ['type' => 'topic', 'info' => 'Guitars'],
'.guru' => ['type' => 'topic', 'info' => 'generic expertise'],
'.hair' => ['type' => 'topic', 'info' => ''],
'.hangout' => ['type' => 'topic', 'info' => ''],
'.health' => ['type' => 'topic', 'info' => ''],
'.healthcare' => ['type' => 'topic', 'info' => 'healthcare industry'],
'.help' => ['type' => 'topic', 'info' => 'help sites'],
'.here' => ['type' => 'topic', 'info' => 'generic geographic'],
'.hiphop' => ['type' => 'topic', 'info' => 'Hip hop culture'],
'.hiv' => ['type' => 'topic', 'info' => 'AIDS and HIV'],
'.hockey' => ['type' => 'topic', 'info' => 'hockey'],
'.holdings' => ['type' => 'topic', 'info' => 'real estate or financial business'],
'.holiday' => ['type' => 'topic', 'info' => 'holiday gift industry'],
'.homegoods' => ['type' => 'topic', 'info' => ''],
'.homes' => ['type' => 'topic', 'info' => 'real estate professionals'],
'.homesense' => ['type' => 'topic', 'info' => ''],
'.horse' => ['type' => 'topic', 'info' => 'horse-related businesses and interest'],
'.hospital' => ['type' => 'topic', 'info' => ''],
'.host' => ['type' => 'topic', 'info' => 'network companies'],
'.hosting' => ['type' => 'topic', 'info' => ''],
'.hot' => ['type' => 'topic', 'info' => ''],
'.hotels' => ['type' => 'topic', 'info' => ''],
'.house' => ['type' => 'topic', 'info' => 'real estate and construction businesses'],
'.how' => ['type' => 'topic', 'info' => 'how-to guides'],
'.ice' => ['type' => 'topic', 'info' => ''],
'.icu' => ['type' => 'topic', 'info' => 'entrepreneurs and business owners'],
'.industries' => ['type' => 'topic', 'info' => 'industrial businesses'],
'.info' => ['type' => 'topic', 'info' => 'information'],
'.ing' => ['type' => 'topic', 'info' => 'Verbal suffix: e.g., "jump.ing".'],
'.ink' => ['type' => 'topic', 'info' => 'creative printing or tattooing'],
'.institute' => ['type' => 'topic', 'info' => ''],
'.insurance' => ['type' => 'topic', 'info' => ''],
'.insure' => ['type' => 'topic', 'info' => 'Insurance companies'],
'.international' => ['type' => 'topic', 'info' => 'international entities'],
'.investments' => ['type' => 'topic', 'info' => 'financial'],
'.jewelry' => ['type' => 'topic', 'info' => 'jewelry stores'],
'.jobs' => ['type' => 'topic', 'info' => 'Employment'],
'.joy' => ['type' => 'topic', 'info' => ''],
'.kim' => ['type' => 'topic', 'info' => 'Kim (Korean surname)'],
'.kitchen' => ['type' => 'topic', 'info' => 'food industry and remodeling'],
'.land' => ['type' => 'topic', 'info' => 'real estate'],
'.latino' => ['type' => 'topic', 'info' => ''],
'.law' => ['type' => 'topic', 'info' => ''],
'.lawyer' => ['type' => 'topic', 'info' => 'lawyers and legal organizations'],
'.lease' => ['type' => 'topic', 'info' => 'financing'],
'.legal' => ['type' => 'topic', 'info' => 'lawyers and legal organizations'],
'.lgbt' => ['type' => 'topic', 'info' => 'the lesbian, gay, bisexual and transgender community'],
'.life' => ['type' => 'topic', 'info' => 'general'],
'.lifeinsurance' => ['type' => 'topic', 'info' => ''],
'.lighting' => ['type' => 'topic', 'info' => 'lighting'],
'.like' => ['type' => 'topic', 'info' => ''],
'.limited' => ['type' => 'topic', 'info' => 'general'],
'.limo' => ['type' => 'topic', 'info' => 'limousine businesses'],
'.link' => ['type' => 'topic', 'info' => 'connecting to information[78]'],
'.live' => ['type' => 'topic', 'info' => ''],
'.living' => ['type' => 'topic', 'info' => ''],
'.loan' => ['type' => 'topic', 'info' => 'banks and lenders'],
'.loans' => ['type' => 'topic', 'info' => 'banks and lenders'],
'.locker' => ['type' => 'topic', 'info' => ''],
'.lol' => ['type' => 'topic', 'info' => 'LOL: laughing out loud'],
'.lotto' => ['type' => 'topic', 'info' => ''],
'.love' => ['type' => 'topic', 'info' => 'dating sites'],
'.luxury' => ['type' => 'topic', 'info' => 'businesses catering to the wealthy'],
'.makeup' => ['type' => 'topic', 'info' => ''],
'.management' => ['type' => 'topic', 'info' => 'business management'],
'.map' => ['type' => 'topic', 'info' => ''],
'.market' => ['type' => 'topic', 'info' => 'marketing services and retailers'],
'.marketing' => ['type' => 'topic', 'info' => 'marketing services'],
'.markets' => ['type' => 'topic', 'info' => 'financial and stock markets'],
'.mba' => ['type' => 'topic', 'info' => 'Masters in Business Administration'],
'.med' => ['type' => 'topic', 'info' => ''],
'.media' => ['type' => 'topic', 'info' => 'general media interests'],
'.meet' => ['type' => 'topic', 'info' => 'social gatherings, meeting new people'],
'.meme' => ['type' => 'topic', 'info' => 'Internet memes'],
'.memorial' => ['type' => 'topic', 'info' => 'memorial sites'],
'.men' => ['type' => 'topic', 'info' => 'men'],
'.menu' => ['type' => 'topic', 'info' => 'restaurants'],
'.mint' => ['type' => 'topic', 'info' => ''],
'.mobi' => ['type' => 'topic', 'info' => 'mobile devices'],
'.mobile' => ['type' => 'topic', 'info' => ''],
'.mobily' => ['type' => 'topic', 'info' => ''],
'.moe' => ['type' => 'topic', 'info' => 'Japanese otaku culture; see moe (slang)'],
'.mom' => ['type' => 'topic', 'info' => ''],
'.money' => ['type' => 'topic', 'info' => 'financial'],
'.mortgage' => ['type' => 'topic', 'info' => 'mortgage lenders'],
'.motorcycles' => ['type' => 'topic', 'info' => 'motorcycles'],
'.mov' => ['type' => 'topic', 'info' => 'Digital video'],
'.movie' => ['type' => 'topic', 'info' => 'movies and cinemas'],
'.museum' => ['type' => 'topic', 'info' => 'museums'],
'.name' => ['type' => 'topic', 'info' => 'individuals, by name'],
'.navy' => ['type' => 'topic', 'info' => 'defense contractors'],
'.network' => ['type' => 'topic', 'info' => 'general'],
'.new' => ['type' => 'topic', 'info' => 'general'],
'.news' => ['type' => 'topic', 'info' => 'news sites'],
'.ngo' => ['type' => 'topic', 'info' => 'Non-governmental organizations. Sold packaged with .ong.'],
'.ninja' => ['type' => 'topic', 'info' => 'general expertise'],
'.now' => ['type' => 'topic', 'info' => ''],
'.observer' => ['type' => 'topic', 'info' => 'news organizations'],
'.off' => ['type' => 'topic', 'info' => ''],
'.one' => ['type' => 'topic', 'info' => 'general'],
'.ong' => ['type' => 'topic', 'info' => 'Non-governmental organizations. Sold packaged with .ngo.'],
'.onl' => ['type' => 'topic', 'info' => 'short for "online"'],
'.online' => ['type' => 'topic', 'info' => 'generic'],
'.ooo' => ['type' => 'topic', 'info' => 'general'],
'.open' => ['type' => 'topic', 'info' => ''],
'.organic' => ['type' => 'topic', 'info' => 'organic gardeners, farmers, foods, etc.'],
'.origins' => ['type' => 'topic', 'info' => ''],
'.page' => ['type' => 'topic', 'info' => ''],
'.partners' => ['type' => 'topic', 'info' => 'businesses'],
'.parts' => ['type' => 'topic', 'info' => 'manufacturing and consumer auto'],
'.party' => ['type' => 'topic', 'info' => 'nightclubs and social gatherings'],
'.pay' => ['type' => 'topic', 'info' => ''],
'.pet' => ['type' => 'topic', 'info' => ''],
'.pharmacy' => ['type' => 'topic', 'info' => 'pharmacies'],
'.phone' => ['type' => 'topic', 'info' => ''],
'.photo' => ['type' => 'topic', 'info' => 'photography and photo-sharing'],
'.photography' => ['type' => 'topic', 'info' => 'photography and photo-sharing'],
'.photos' => ['type' => 'topic', 'info' => 'photography and photo-sharing'],
'.physio' => ['type' => 'topic', 'info' => 'physical therapists'],
'.pics' => ['type' => 'topic', 'info' => 'photography and photo-sharing'],
'.pictures' => ['type' => 'topic', 'info' => 'photography and photo-sharing'],
'.pid' => ['type' => 'topic', 'info' => ''],
'.pin' => ['type' => 'topic', 'info' => ''],
'.pink' => ['type' => 'topic', 'info' => 'those who like the color pink'],
'.pizza' => ['type' => 'topic', 'info' => 'pizza parlors'],
'.place' => ['type' => 'topic', 'info' => 'general'],
'.plumbing' => ['type' => 'topic', 'info' => 'plumbing businesses'],
'.plus' => ['type' => 'topic', 'info' => 'generic'],
'.poker' => ['type' => 'topic', 'info' => 'Poker players and sites'],
'.porn' => ['type' => 'topic', 'info' => 'adult entertainment (pornography)'],
'.post' => ['type' => 'topic', 'info' => 'postal services'],
'.press' => ['type' => 'topic', 'info' => 'publishing and journalism'],
'.prime' => ['type' => 'topic', 'info' => ''],
'.pro' => ['type' => 'topic', 'info' => 'professions/professionals'],
'.productions' => ['type' => 'topic', 'info' => 'studio/art businesses'],
'.prof' => ['type' => 'topic', 'info' => 'Professors, teachers and learning'],
'.promo' => ['type' => 'topic', 'info' => ''],
'.properties' => ['type' => 'topic', 'info' => 'real estate'],
'.property' => ['type' => 'topic', 'info' => 'real estate'],
'.protection' => ['type' => 'topic', 'info' => ''],
'.pub' => ['type' => 'topic', 'info' => 'bars and pubs'],
'.qpon' => ['type' => 'topic', 'info' => 'coupons'],
'.racing' => ['type' => 'topic', 'info' => 'racing'],
'.radio' => ['type' => 'topic', 'info' => ''],
'.read' => ['type' => 'topic', 'info' => ''],
'.realestate' => ['type' => 'topic', 'info' => ''],
'.realtor' => ['type' => 'topic', 'info' => 'realtors'],
'.realty' => ['type' => 'topic', 'info' => ''],
'.recipes' => ['type' => 'topic', 'info' => 'recipes and cooking'],
'.red' => ['type' => 'topic', 'info' => 'those who like the color red'],
'.rehab' => ['type' => 'topic', 'info' => 'Rehab centers and support sites'],
'.reit' => ['type' => 'topic', 'info' => 'real estate investment trusts'],
'.ren' => ['type' => 'topic', 'info' => 'Renren users (ren means "people/person" in Mandarin Chinese pinyin)'],
'.rent' => ['type' => 'topic', 'info' => 'Real estate professionals and small businesses'],
'.rentals' => ['type' => 'topic', 'info' => 'short-term ownership'],
'.repair' => ['type' => 'topic', 'info' => 'general repair/maintenance businesses'],
'.report' => ['type' => 'topic', 'info' => 'business services'],
'.republican' => ['type' => 'topic', 'info' => 'Republican Party politics'],
'.rest' => ['type' => 'topic', 'info' => 'Restaurants and related industry'],
'.restaurant' => ['type' => 'topic', 'info' => 'restaurants'],
'.review' => ['type' => 'topic', 'info' => 'public reviews'],
'.reviews' => ['type' => 'topic', 'info' => 'public reviews'],
'.rich' => ['type' => 'topic', 'info' => 'businesses catering to the wealthy'],
'.rip' => ['type' => 'topic', 'info' => 'memorial sites'],
'.rocks' => ['type' => 'topic', 'info' => 'general'],
'.rodeo' => ['type' => 'topic', 'info' => 'Rodeo interest'],
'.room' => ['type' => 'topic', 'info' => ''],
'.rugby' => ['type' => 'topic', 'info' => ''],
'.run' => ['type' => 'topic', 'info' => 'running and jogging'],
'.safe' => ['type' => 'topic', 'info' => ''],
'.sale' => ['type' => 'topic', 'info' => 'retail'],
'.save' => ['type' => 'topic', 'info' => ''],
'.scholarships' => ['type' => 'topic', 'info' => 'scholarship related'],
'.school' => ['type' => 'topic', 'info' => 'schools'],
'.science' => ['type' => 'topic', 'info' => 'science-related sites'],
'.search' => ['type' => 'topic', 'info' => ''],
'.secure' => ['type' => 'topic', 'info' => ''],
'.security' => ['type' => 'topic', 'info' => ''],
'.select' => ['type' => 'topic', 'info' => ''],
'.services' => ['type' => 'topic', 'info' => 'business services'],
'.sex' => ['type' => 'topic', 'info' => 'adult entertainment (pornography)'],
'.sexy' => ['type' => 'topic', 'info' => 'adult entertainment'],
'.shoes' => ['type' => 'topic', 'info' => 'shoes'],
'.shop' => ['type' => 'topic', 'info' => ''],
'.shopping' => ['type' => 'topic', 'info' => ''],
'.show' => ['type' => 'topic', 'info' => 'entertainment and vlogs'],
'.showtime' => ['type' => 'topic', 'info' => ''],
'.silk' => ['type' => 'topic', 'info' => ''],
'.singles' => ['type' => 'topic', 'info' => 'online dating'],
'.site' => ['type' => 'topic', 'info' => 'general'],
'.ski' => ['type' => 'topic', 'info' => ''],
'.skin' => ['type' => 'topic', 'info' => ''],
'.sky' => ['type' => 'topic', 'info' => ''],
'.sling' => ['type' => 'topic', 'info' => ''],
'.smile' => ['type' => 'topic', 'info' => ''],
'.soccer' => ['type' => 'topic', 'info' => 'soccer'],
'.social' => ['type' => 'topic', 'info' => 'general interest'],
'.software' => ['type' => 'topic', 'info' => 'computer software'],
'.solar' => ['type' => 'topic', 'info' => 'solar-power'],
'.solutions' => ['type' => 'topic', 'info' => 'business services'],
'.song' => ['type' => 'topic', 'info' => ''],
'.space' => ['type' => 'topic', 'info' => 'as a creative space'],
'.spot' => ['type' => 'topic', 'info' => ''],
'.spreadbetting' => ['type' => 'topic', 'info' => ''],
'.storage' => ['type' => 'topic', 'info' => ''],
'.store' => ['type' => 'topic', 'info' => 'stores'],
'.stream' => ['type' => 'topic', 'info' => ''],
'.studio' => ['type' => 'topic', 'info' => 'art, fitness, & entertainment'],
'.study' => ['type' => 'topic', 'info' => ''],
'.style' => ['type' => 'topic', 'info' => 'fashion'],
'.sucks' => ['type' => 'topic', 'info' => 'gripe sites'],
'.supplies' => ['type' => 'topic', 'info' => 'manufacturing industries'],
'.supply' => ['type' => 'topic', 'info' => 'manufacturing industries'],
'.support' => ['type' => 'topic', 'info' => 'help pages'],
'.surf' => ['type' => 'topic', 'info' => 'surfing'],
'.surgery' => ['type' => 'topic', 'info' => 'healthcare industry'],
'.systems' => ['type' => 'topic', 'info' => 'technology'],
'.talk' => ['type' => 'topic', 'info' => ''],
'.tattoo' => ['type' => 'topic', 'info' => 'tattoo aficionados'],
'.tax' => ['type' => 'topic', 'info' => 'financial'],
'.taxi' => ['type' => 'topic', 'info' => 'taxi services'],
'.team' => ['type' => 'topic', 'info' => 'team sports'],
'.tech' => ['type' => 'topic', 'info' => 'technology'],
'.technology' => ['type' => 'topic', 'info' => 'technology'],
'.tel' => ['type' => 'topic', 'info' => 'Internet communication services'],
'.tennis' => ['type' => 'topic', 'info' => 'tennis'],
'.theater' => ['type' => 'topic', 'info' => 'theaters and cinemas'],
'.theatre' => ['type' => 'topic', 'info' => ''],
'.tickets' => ['type' => 'topic', 'info' => ''],
'.tips' => ['type' => 'topic', 'info' => 'general help topics'],
'.tires' => ['type' => 'topic', 'info' => 'tire manufacturers'],
'.today' => ['type' => 'topic', 'info' => 'general'],
'.tools' => ['type' => 'topic', 'info' => 'manufacturing industries'],
'.top' => ['type' => 'topic', 'info' => 'general'],
'.tours' => ['type' => 'topic', 'info' => 'tourism'],
'.town' => ['type' => 'topic', 'info' => 'generic geographic'],
'.toys' => ['type' => 'topic', 'info' => 'toy businesses'],
'.trade' => ['type' => 'topic', 'info' => 'businesses'],
'.trading' => ['type' => 'topic', 'info' => ''],
'.training' => ['type' => 'topic', 'info' => 'sports and fitness'],
'.travel' => ['type' => 'topic', 'info' => 'travel and tourism industry related sites'],
'.travelersinsurance' => ['type' => 'topic', 'info' => ''],
'.trust' => ['type' => 'topic', 'info' => ''],
'.tube' => ['type' => 'topic', 'info' => ''],
'.tunes' => ['type' => 'topic', 'info' => ''],
'.uconnect' => ['type' => 'topic', 'info' => ''],
'.university' => ['type' => 'topic', 'info' => 'young adults, university life'],
'.vacations' => ['type' => 'topic', 'info' => 'travel'],
'.ventures' => ['type' => 'topic', 'info' => 'funding for start-ups'],
'.vet' => ['type' => 'topic', 'info' => 'veterans and veterinarians'],
'.video' => ['type' => 'topic', 'info' => 'video sharing'],
'.villas' => ['type' => 'topic', 'info' => 'real estate and/or travel businesses'],
'.vip' => ['type' => 'topic', 'info' => ''],
'.vision' => ['type' => 'topic', 'info' => 'eye-care businesses'],
'.vodka' => ['type' => 'topic', 'info' => 'Vodka-related businesses and interest'],
'.vote' => ['type' => 'topic', 'info' => 'democratic elections and campaign websites'],
'.voting' => ['type' => 'topic', 'info' => 'polling sites'],
'.voyage' => ['type' => 'topic', 'info' => 'travel'],
'.wang' => ['type' => 'topic', 'info' => 'general'],
'.watch' => ['type' => 'topic', 'info' => 'Watches'],
'.watches' => ['type' => 'topic', 'info' => ''],
'.weather' => ['type' => 'topic', 'info' => ''],
'.webcam' => ['type' => 'topic', 'info' => 'Web cam shows and video sharing'],
'.website' => ['type' => 'topic', 'info' => 'general'],
'.wed' => ['type' => 'topic', 'info' => 'engaged couples and wedding-oriented businesses'],
'.wedding' => ['type' => 'topic', 'info' => 'wedding-oriented businesses'],
'.whoswho' => ['type' => 'topic', 'info' => 'general'],
'.wiki' => ['type' => 'topic', 'info' => 'wikis'],
'.win' => ['type' => 'topic', 'info' => 'games, Microsoft Windows'],
'.wine' => ['type' => 'topic', 'info' => 'Wine'],
'.winners' => ['type' => 'topic', 'info' => ''],
'.work' => ['type' => 'topic', 'info' => 'general'],
'.works' => ['type' => 'topic', 'info' => 'general'],
'.world' => ['type' => 'topic', 'info' => 'general'],
'.wow' => ['type' => 'topic', 'info' => ''],
'.wtf' => ['type' => 'topic', 'info' => 'general'],
'.xxx' => ['type' => 'topic', 'info' => 'adult entertainment (pornography)'],
'.xyz' => ['type' => 'topic', 'info' => 'general'],
'.yachts' => ['type' => 'topic', 'info' => ''],
'.yoga' => ['type' => 'topic', 'info' => 'yoga'],
'.you' => ['type' => 'topic', 'info' => ''],
'.zero' => ['type' => 'topic', 'info' => ''],
'.zone' => ['type' => 'topic', 'info' => 'general'],
'.shouji' => ['type' => 'topic', 'info' => 'mobile phone'],
'.tushu' => ['type' => 'topic', 'info' => 'books'],
'.wanggou' => ['type' => 'topic', 'info' => 'online shopping'],
'.weibo' => ['type' => 'topic', 'info' => 'microblogging'],
'.xihuan' => ['type' => 'topic', 'info' => 'like'],
'.arte' => ['type' => 'topic', 'info' => ''],
'.clinique' => ['type' => 'topic', 'info' => '"hospital"'],
'.luxe' => ['type' => 'topic', 'info' => '"luxury"'],
'.maison' => ['type' => 'topic', 'info' => '"house"'],
'.moi' => ['type' => 'topic', 'info' => '"me"'],
'.rsvp' => ['type' => 'topic', 'info' => 'Invitations and replies'],
'.sarl' => ['type' => 'topic', 'info' => 'Société à responsabilité limitée, Francophone Limited liability company'],
'.epost' => ['type' => 'topic', 'info' => 'e-mail'],
'.gmbh' => ['type' => 'topic', 'info' => 'GmbH'],
'.haus' => ['type' => 'topic', 'info' => '"house"'],
'.immobilien' => ['type' => 'topic', 'info' => '"real estate"'],
'.jetzt' => ['type' => 'topic', 'info' => '"now"'],
'.kaufen' => ['type' => 'topic', 'info' => '"buy"'],
'.kinder' => ['type' => 'topic', 'info' => 'children'],
'.reise' => ['type' => 'topic', 'info' => '"travel"'],
'.reisen' => ['type' => 'topic', 'info' => '"traveling"'],
'.schule' => ['type' => 'topic', 'info' => '"school"'],
'.versicherung' => ['type' => 'topic', 'info' => '"insurance"'],
'.desi' => ['type' => 'topic', 'info' => 'Hindi for the peoples and cultures of South Asia'],
'.shiksha' => ['type' => 'topic', 'info' => 'Hindi for "education".'],
'.casa' => ['type' => 'topic', 'info' => '"house"'],
'.immo' => ['type' => 'topic', 'info' => 'French, German and Italian abbreviation for "real estate"'],
'.moda' => ['type' => 'topic', 'info' => '"fashion"'],
'.voto' => ['type' => 'topic', 'info' => '"vote", for election and campaign websites'],
'.bom' => ['type' => 'topic', 'info' => 'good'],
'.passagens' => ['type' => 'topic', 'info' => 'ticket'],
'.abogado' => ['type' => 'topic', 'info' => '"lawyer"'],
'.gratis' => ['type' => 'topic', 'info' => '"free"'],
'.futbol' => ['type' => 'topic', 'info' => 'Football (soccer for United States)'],
'.hoteles' => ['type' => 'topic', 'info' => 'hotels'],
'.juegos' => ['type' => 'topic', 'info' => '"games"'],
'.ltda' => ['type' => 'topic', 'info' => 'companies in South America'],
'.soy' => ['type' => 'topic', 'info' => '"I am" Also refers to the soybean and its food derivatives'],
'.tienda' => ['type' => 'topic', 'info' => '"shop", "store"'],
'.uno' => ['type' => 'topic', 'info' => '"one", for websites targeting Spanish speaking consumers'],
'.viajes' => ['type' => 'topic', 'info' => '"travel"'],
'.vuelos' => ['type' => 'topic', 'info' => 'flights'],
'.africa' => ['type' => 'geographic', 'info' => 'Africa'],
'.capetown' => ['type' => 'geographic', 'info' => 'Cape Town, South Africa'],
'.durban' => ['type' => 'geographic', 'info' => 'Durban, South Africa'],
'.joburg' => ['type' => 'geographic', 'info' => 'Johannesburg, South Africa'],
'.abudhabi' => ['type' => 'geographic', 'info' => 'Abu Dhabi'],
'.arab' => ['type' => 'geographic', 'info' => 'League of Arab States'],
'.asia' => ['type' => 'geographic', 'info' => 'Asia-Pacific region'],
'.doha' => ['type' => 'geographic', 'info' => 'Doha'],
'.dubai' => ['type' => 'geographic', 'info' => 'Dubai'],
'.krd' => ['type' => 'geographic', 'info' => 'Kurdistan'],
'.kyoto' => ['type' => 'geographic', 'info' => 'Kyoto, Japan'],
'.nagoya' => ['type' => 'geographic', 'info' => 'Nagoya, Japan'],
'.okinawa' => ['type' => 'geographic', 'info' => 'Okinawa, Japan'],
'.osaka' => ['type' => 'geographic', 'info' => 'Osaka, Japan'],
'.ryukyu' => ['type' => 'geographic', 'info' => 'Ryukyu Islands, Japan'],
'.taipei' => ['type' => 'geographic', 'info' => 'Taipei, Taiwan'],
'.tatar' => ['type' => 'geographic', 'info' => 'Tatar peoples and places'],
'.tokyo' => ['type' => 'geographic', 'info' => 'Tokyo, Japan'],
'.yokohama' => ['type' => 'geographic', 'info' => 'Yokohama, Japan'],
'.alsace' => ['type' => 'geographic', 'info' => 'Alsace, France'],
'.amsterdam' => ['type' => 'geographic', 'info' => 'Amsterdam, The Netherlands'],
'.bcn' => ['type' => 'geographic', 'info' => 'Barcelona, Spain'],
'.barcelona' => ['type' => 'geographic', 'info' => 'Barcelona, Spain'],
'.bayern' => ['type' => 'geographic', 'info' => 'Bavaria, Germany'],
'.berlin' => ['type' => 'geographic', 'info' => 'Berlin, Germany'],
'.brussels' => ['type' => 'geographic', 'info' => 'Brussels, Belgium'],
'.budapest' => ['type' => 'geographic', 'info' => 'Budapest, Hungary'],
'.bzh' => ['type' => 'geographic', 'info' => 'Brittany, France ; Breton language and culture'],
'.cat' => ['type' => 'geographic', 'info' => 'Catalonia; Catalan language and culture'],
'.cologne' => ['type' => 'geographic', 'info' => 'Cologne, Germany'],
'.corsica' => ['type' => 'geographic', 'info' => 'Corsica, France'],
'.cymru' => ['type' => 'geographic', 'info' => 'Wales'],
'.eus' => ['type' => 'geographic', 'info' => 'Basque, Spain and France'],
'.frl' => ['type' => 'geographic', 'info' => 'Friesland, Netherlands'],
'.gal' => ['type' => 'geographic', 'info' => 'Galicia, Spain'],
'.gent' => ['type' => 'geographic', 'info' => 'Ghent, Belgium'],
'.hamburg' => ['type' => 'geographic', 'info' => 'Hamburg, Germany'],
'.helsinki' => ['type' => 'geographic', 'info' => 'Helsinki'],
'.irish' => ['type' => 'geographic', 'info' => 'Ireland; global Irish community'],
'.ist' => ['type' => 'geographic', 'info' => 'İstanbul, Turkey'],
'.istanbul' => ['type' => 'geographic', 'info' => 'İstanbul, Turkey'],
'.koeln' => ['type' => 'geographic', 'info' => 'Cologne, Germany'],
'.london' => ['type' => 'geographic', 'info' => 'London, United Kingdom'],
'.madrid' => ['type' => 'geographic', 'info' => 'Madrid, Spain'],
'.moscow (ru)' => ['type' => 'geographic', 'info' => 'Moscow, Russia'],
'.nrw' => ['type' => 'geographic', 'info' => 'North Rhine-Westphalia, Germany'],
'.paris' => ['type' => 'geographic', 'info' => 'Paris, France'],
'.ruhr' => ['type' => 'geographic', 'info' => 'Ruhr, Germany'],
'.saarland' => ['type' => 'geographic', 'info' => 'Saarland, Germany'],
'.scot' => ['type' => 'geographic', 'info' => 'Scotland'],
'.stockholm' => ['type' => 'geographic', 'info' => 'Stockholm'],
'.swiss' => ['type' => 'geographic', 'info' => 'Switzerland'],
'.tirol' => ['type' => 'geographic', 'info' => 'Tyrol, Austria'],
'.vlaanderen' => ['type' => 'geographic', 'info' => 'Flanders, Belgium'],
'.wales' => ['type' => 'geographic', 'info' => 'Wales'],
'.wien' => ['type' => 'geographic', 'info' => 'Vienna, Austria'],
'.zuerich' => ['type' => 'geographic', 'info' => 'Zurich, Switzerland'],
'.boston' => ['type' => 'geographic', 'info' => 'Boston, Massachusetts'],
'.miami' => ['type' => 'geographic', 'info' => 'Miami, Florida'],
'.nyc' => ['type' => 'geographic', 'info' => 'New York City, New York'],
'.quebec' => ['type' => 'geographic', 'info' => 'Québec, Canada'],
'.vegas' => ['type' => 'geographic', 'info' => 'Las Vegas, Nevada'],
'.kiwi' => ['type' => 'geographic', 'info' => 'New Zealanders'],
'.melbourne' => ['type' => 'geographic', 'info' => 'Melbourne, Australia'],
'.sydney' => ['type' => 'geographic', 'info' => 'Sydney, Australia'],
'.lat' => ['type' => 'geographic', 'info' => 'Latin America'],
'.rio' => ['type' => 'geographic', 'info' => 'Rio de Janeiro, Brazil'],
'.aaa' => ['type' => 'brand', 'info' => 'American Automobile Association, Inc.'],
'.aarp' => ['type' => 'brand', 'info' => 'AARP'],
'.abarth' => ['type' => 'brand', 'info' => 'Fiat Chrysler Automobiles N.V. (Abarth)'],
'.abb' => ['type' => 'brand', 'info' => 'ABB Ltd'],
'.abbott' => ['type' => 'brand', 'info' => 'Abbott Laboratories, Inc.'],
'.abbvie' => ['type' => 'brand', 'info' => 'AbbVie Inc.'],
'.abc' => ['type' => 'brand', 'info' => 'American Broadcasting Companies, Inc.[164]'],
'.accenture' => ['type' => 'brand', 'info' => 'Accenture plc'],
'.aco' => ['type' => 'brand', 'info' => 'ACO Severin Ahlmann GmbH & Co. KG'],
'.aeg' => ['type' => 'brand', 'info' => 'Aktiebolaget Electrolux'],
'.aetna' => ['type' => 'brand', 'info' => 'Aetna Life Insurance Company'],
'.afl' => ['type' => 'brand', 'info' => 'Australian Football League'],
'.agakhan' => ['type' => 'brand', 'info' => 'Fondation Aga Khan (Aga Khan Foundation)'],
'.aig' => ['type' => 'brand', 'info' => 'American International Group, Inc.'],
'.aigo' => ['type' => 'brand', 'info' => 'aigo Digital Technology Co, Ltd.'],
'.airbus' => ['type' => 'brand', 'info' => 'Airbus S.A.S.'],
'.airtel' => ['type' => 'brand', 'info' => 'Bharti Airtel Limited'],
'.akdn' => ['type' => 'brand', 'info' => 'Fondation Aga Khan (Aga Khan Foundation)'],
'.alfaromeo' => ['type' => 'brand', 'info' => 'Fiat Chrysler Automobiles N.V. (Alfa Romeo)'],
'.alibaba' => ['type' => 'brand', 'info' => 'Alibaba Group Holding Limited'],
'.alipay' => ['type' => 'brand', 'info' => 'Alibaba Group Holding Limited'],
'.allfinanz' => ['type' => 'brand', 'info' => 'Allfinanz Deutsche Vermögensberatung Aktiengesellschaft'],
'.allstate' => ['type' => 'brand', 'info' => 'Allstate Fire and Casualty Insurance Company'],
'.ally' => ['type' => 'brand', 'info' => 'Ally Financial Inc.'],
'.alstom' => ['type' => 'brand', 'info' => 'ALSTOM'],
'.americanexpress' => ['type' => 'brand', 'info' => 'American Express Travel Related Services Company, Inc.'],
'.amex' => ['type' => 'brand', 'info' => 'American Express Travel Related Services Company, Inc.'],
'.amica' => ['type' => 'brand', 'info' => 'Amica Mutual Insurance Company'],
'.android' => ['type' => 'brand', 'info' => 'Google (Android)'],
'.anz' => ['type' => 'brand', 'info' => 'Australia and New Zealand Banking Group Limited'],
'.aol' => ['type' => 'brand', 'info' => 'AOL Inc.'],
'.apple' => ['type' => 'brand', 'info' => 'Apple Inc.'],
'.aquarelle' => ['type' => 'brand', 'info' => 'Aquarelle.com Group'],
'.aramco' => ['type' => 'brand', 'info' => 'Aramco Services Company'],
'.audi' => ['type' => 'brand', 'info' => 'AUDI Aktiengesellschaft'],
'.auspost' => ['type' => 'brand', 'info' => 'Australian Postal Corporation'],
'.axa' => ['type' => 'brand', 'info' => 'AXA'],
'.azure' => ['type' => 'brand', 'info' => 'Microsoft Corporation'],
'.baidu' => ['type' => 'brand', 'info' => 'Baidu, Inc.'],
'.bananarepublic' => ['type' => 'brand', 'info' => 'The Gap, Inc.'],
'.barclaycard' => ['type' => 'brand', 'info' => 'Barclays'],
'.barclays' => ['type' => 'brand', 'info' => 'Barclays'],
'.basketball' => ['type' => 'brand', 'info' => 'FIBA'],
'.bauhaus' => ['type' => 'brand', 'info' => 'Werkhaus GmbH'],
'.bbc' => ['type' => 'brand', 'info' => 'British Broadcasting Corporation'],
'.bbt' => ['type' => 'brand', 'info' => 'BB&T Corporation'],
'.bbva' => ['type' => 'brand', 'info' => 'Banco Bilbao Vizcaya Argentaria, S.A.'],
'.bcg' => ['type' => 'brand', 'info' => 'The Boston Consulting Group, Inc.'],
'.bentley' => ['type' => 'brand', 'info' => 'Bentley Motors Limited'],
'.bharti' => ['type' => 'brand', 'info' => 'Bharti Enterprises (Holding) Private Limited'],
'.bing' => ['type' => 'brand', 'info' => 'Microsoft Corporation'],
'.blanco' => ['type' => 'brand', 'info' => 'BLANCO GmbH + Co KG'],
'.bloomberg' => ['type' => 'brand', 'info' => 'Bloomberg IP Holdings LLC'],
'.bms' => ['type' => 'brand', 'info' => 'Bristol-Myers Squibb Company'],
'.bmw' => ['type' => 'brand', 'info' => 'Bayerische Motoren Werke AG'],
'.bnl' => ['type' => 'brand', 'info' => 'Banca Nazionale del Lavoro'],
'.bnpparibas' => ['type' => 'brand', 'info' => 'BNP Paribas'],
'.boehringer' => ['type' => 'brand', 'info' => 'Boehringer Ingelheim International GmbH'],
'.bond' => ['type' => 'brand', 'info' => 'Bond University Limited'],
'.booking' => ['type' => 'brand', 'info' => 'Booking.com B.V.'],
'.bosch' => ['type' => 'brand', 'info' => 'Robert Bosch GmbH'],
'.bostik' => ['type' => 'brand', 'info' => 'Bostik SA'],
'.bradesco' => ['type' => 'brand', 'info' => 'Bradesco'],
'.bridgestone' => ['type' => 'brand', 'info' => 'Bridgestone Corporation'],
'.brother' => ['type' => 'brand', 'info' => 'Brother Industries, Ltd.'],
'.bugatti' => ['type' => 'brand', 'info' => 'Bugatti International SA'],
'.cal' => ['type' => 'brand', 'info' => 'Google (Google Calendar)'],
'.calvinklein' => ['type' => 'brand', 'info' => 'PVH gTLD Holdings LLC'],
'.canon' => ['type' => 'brand', 'info' => 'Canon Inc.'],
'.capitalone' => ['type' => 'brand', 'info' => 'Capital One Financial Corporation'],
'.caravan' => ['type' => 'brand', 'info' => 'Caravan International, Inc.'],
'.cartier' => ['type' => 'brand', 'info' => 'Richemont DNS Inc.'],
'.cba' => ['type' => 'brand', 'info' => 'Commonwealth Bank Of Australia'],
'.cbn' => ['type' => 'brand', 'info' => 'The Christian Broadcasting Network, Inc.'],
'.cbre' => ['type' => 'brand', 'info' => 'CBRE, Inc.'],
'.cbs' => ['type' => 'brand', 'info' => 'CBS Domains Inc.'],
'.cern' => ['type' => 'brand', 'info' => 'CERN'],
'.cfa' => ['type' => 'brand', 'info' => 'CFA Institute'],
'.chanel' => ['type' => 'brand', 'info' => 'Chanel International B.V.'],
'.chase' => ['type' => 'brand', 'info' => 'JPMorgan Chase Bank, National Association'],
'.chintai' => ['type' => 'brand', 'info' => 'Chintai Corporation'],
'.chrome' => ['type' => 'brand', 'info' => 'Google (Google Chrome)'],
'.chrysler' => ['type' => 'brand', 'info' => 'FCA US LLC'],
'.cisco' => ['type' => 'brand', 'info' => 'Cisco Technology, Inc.'],
'.citadel' => ['type' => 'brand', 'info' => 'Citadel Domain LLC'],
'.citi' => ['type' => 'brand', 'info' => 'Citigroup Inc.'],
'.citic' => ['type' => 'brand', 'info' => 'CITIC Group'],
'.clubmed' => ['type' => 'brand', 'info' => 'Club Méditerranée S.A.'],
'.comcast' => ['type' => 'brand', 'info' => 'Comcast IP Holdings I, LLC'],
'.commbank' => ['type' => 'brand', 'info' => 'Commonwealth Bank Of Australia'],
'.creditunion' => ['type' => 'brand', 'info' => 'CUNA Performance Resources, LLC'],
'.crown' => ['type' => 'brand', 'info' => 'Crown Equipment Corporation'],
'.crs' => ['type' => 'brand', 'info' => 'Federated Co-operatives Limited (Co-Operative Retailing System)'],
'.csc' => ['type' => 'brand', 'info' => 'DXC Technology (Formerly CSC)'],
'.cuisinella' => ['type' => 'brand', 'info' => 'Société Alsacienne de Meubles (Cuisinella)'],
'.dabur' => ['type' => 'brand', 'info' => 'Dabur India Limited'],
'.datsun' => ['type' => 'brand', 'info' => 'Nissan Motor Co., Ltd.'],
'.dealer' => ['type' => 'brand', 'info' => 'Dealer Dot Com, Inc.'],
'.dell' => ['type' => 'brand', 'info' => 'Dell Inc.'],
'.deloitte' => ['type' => 'brand', 'info' => 'Deloitte Touche Tohmatsu'],
'.delta' => ['type' => 'brand', 'info' => 'Delta Air Lines, Inc.'],
'.dhl' => ['type' => 'brand', 'info' => 'Deutsche Post AG'],
'.discover' => ['type' => 'brand', 'info' => 'Discover Financial Services'],
'.dish' => ['type' => 'brand', 'info' => 'Dish DBS Corporation'],
'.dnp' => ['type' => 'brand', 'info' => 'Dai Nippon Printing Co.'],
'.dodge' => ['type' => 'brand', 'info' => 'FCA US LLC (Dodge)'],
'.dunlop' => ['type' => 'brand', 'info' => 'The Goodyear Tire & Rubber Company'],
'.dupont' => ['type' => 'brand', 'info' => 'E. I. du Pont de Nemours and Company'],
'.dvag' => ['type' => 'brand', 'info' => 'Deutsche Vermögensberatung Aktiengesellschaft'],
'.edeka' => ['type' => 'brand', 'info' => 'Edeka'],
'.emerck' => ['type' => 'brand', 'info' => 'Merck KGaA'],
'.epson' => ['type' => 'brand', 'info' => 'Seiko Epson Corporation'],
'.ericsson' => ['type' => 'brand', 'info' => 'Telefonaktiebolaget L M Ericsson'],
'.erni' => ['type' => 'brand', 'info' => 'ERNI Group Holding AG'],
'.esurance' => ['type' => 'brand', 'info' => 'Esurance Insurance Company'],
'.etisalat' => ['type' => 'brand', 'info' => 'Emirates Telecommunications Corporation (trading as Etisalat)'],
'.eurovision' => ['type' => 'brand', 'info' => 'European Broadcasting Union (EBU)'],
'.everbank' => ['type' => 'brand', 'info' => 'EverBank'],
'.extraspace' => ['type' => 'brand', 'info' => 'Extra Space Storage LLC'],
'.fage' => ['type' => 'brand', 'info' => 'Fage International S.A.'],
'.fairwinds' => ['type' => 'brand', 'info' => 'FairWinds Partners, LLC'],
'.farmers' => ['type' => 'brand', 'info' => 'Farmers Insurance Exchange'],
'.fedex' => ['type' => 'brand', 'info' => 'FedEx Corporation'],
'.ferrari' => ['type' => 'brand', 'info' => 'Fiat Chrysler Automobiles N.V. (Ferrari)'],
'.ferrero' => ['type' => 'brand', 'info' => 'Ferrero Trading Lux S.A.'],
'.fiat' => ['type' => 'brand', 'info' => 'Fiat Chrysler Automobiles N.V.'],
'.fidelity' => ['type' => 'brand', 'info' => 'Fidelity Brokerage Services LLC'],
'.firestone' => ['type' => 'brand', 'info' => 'Bridgestone Licensing Services, Inc.'],
'.firmdale' => ['type' => 'brand', 'info' => 'Firmdale Holdings'],
'.flickr' => ['type' => 'brand', 'info' => 'Yahoo! Domain Services Inc.'],
'.flir' => ['type' => 'brand', 'info' => 'FLIR Systems, Inc.'],
'.flsmidth' => ['type' => 'brand', 'info' => 'FLSmidth A/S'],
'.ford' => ['type' => 'brand', 'info' => 'Ford Motor Company'],
'.fox' => ['type' => 'brand', 'info' => 'FOX Registry, LLC'],
'.fresenius' => ['type' => 'brand', 'info' => 'Fresenius Immobilien-Verwaltungs-GmbH'],
'.forex' => ['type' => 'brand', 'info' => 'Dotforex Registry Ltd'],
'.frogans' => ['type' => 'brand', 'info' => 'OP3FT'],
'.frontier' => ['type' => 'brand', 'info' => 'Frontier Communications Corporation'],
'.fujitsu' => ['type' => 'brand', 'info' => 'Fujitsu Limited'],
'.fujixerox' => ['type' => 'brand', 'info' => 'Xerox DNHC LLC'],
'.gallo' => ['type' => 'brand', 'info' => 'Gallo Vineyards, Inc.'],
'.gallup' => ['type' => 'brand', 'info' => 'Gallup, Inc.'],
'.gap' => ['type' => 'brand', 'info' => 'The Gap, Inc.'],
'.gbiz' => ['type' => 'brand', 'info' => 'Google'],
'.gea' => ['type' => 'brand', 'info' => 'GEA Group Aktiengesellschaft'],
'.genting' => ['type' => 'brand', 'info' => 'Resorts World Inc. Pte. Ltd.'],
'.giving' => ['type' => 'brand', 'info' => 'Giving Limited'],
'.gle' => ['type' => 'brand', 'info' => 'Google'],
'.globo' => ['type' => 'brand', 'info' => 'Grupo Globo'],
'.gmail' => ['type' => 'brand', 'info' => 'Google (Gmail)'],
'.gmo' => ['type' => 'brand', 'info' => 'GMO Internet'],
'.gmx' => ['type' => 'brand', 'info' => '1&1 Mail & Media (Global Message Exchange)'],
'.godaddy' => ['type' => 'brand', 'info' => 'Go Daddy East, LLC'],
'.goldpoint' => ['type' => 'brand', 'info' => 'Yodobashi Camera Co., Ltd.'],
'.goodyear' => ['type' => 'brand', 'info' => 'The Goodyear Tire & Rubber Company'],
'.google' => ['type' => 'brand', 'info' => 'Google'],
'.grainger' => ['type' => 'brand', 'info' => 'Grainger Registry Services, LLC'],
'.guardian' => ['type' => 'brand', 'info' => 'The Guardian Life Insurance Company of America'],
'.gucci' => ['type' => 'brand', 'info' => 'Guccio Gucci S.p.a.'],
'.hbo' => ['type' => 'brand', 'info' => 'HBO Registry Services, Inc.'],
'.hdfc' => ['type' => 'brand', 'info' => 'Housing Development Finance Corporation Limited'],
'.hdfcbank' => ['type' => 'brand', 'info' => 'HDFC Bank Limited'],
'.hermes' => ['type' => 'brand', 'info' => 'Hermes International'],
'.hisamitsu' => ['type' => 'brand', 'info' => 'Hisamitsu Pharmaceutical Co., Inc.'],
'.hitachi' => ['type' => 'brand', 'info' => 'Hitachi, Ltd.'],
'.hkt' => ['type' => 'brand', 'info' => 'PCCW-HKT DataCom Services Limited'],
'.honda' => ['type' => 'brand', 'info' => 'Honda Motor Co., Ltd.'],
'.honeywell' => ['type' => 'brand', 'info' => 'Honeywell GTLD LLC'],
'.hotmail' => ['type' => 'brand', 'info' => 'Microsoft Corporation'],
'.hsbc' => ['type' => 'brand', 'info' => 'HSBC'],
'.hughes' => ['type' => 'brand', 'info' => 'Hughes Satellite Systems Corporation'],
'.hyatt' => ['type' => 'brand', 'info' => 'Hyatt GTLD, L.L.C.'],
'.hyundai' => ['type' => 'brand', 'info' => 'Hyundai Motor Company'],
'.ibm' => ['type' => 'brand', 'info' => 'IBM'],
'.ieee' => ['type' => 'brand', 'info' => 'IEEE Global LLC'],
'.ifm' => ['type' => 'brand', 'info' => 'ifm electronic gmbh'],
'.ikano' => ['type' => 'brand', 'info' => 'Ikano S.A.'],
'.imdb' => ['type' => 'brand', 'info' => 'Amazon Registry Services, Inc.'],
'.infiniti' => ['type' => 'brand', 'info' => 'Nissan Motor Co., Ltd. (Infiniti)'],
'.intel' => ['type' => 'brand', 'info' => 'Intel Corporation'],
'.intuit' => ['type' => 'brand', 'info' => 'Intuit Administrative Services, Inc.'],
'.ipiranga' => ['type' => 'brand', 'info' => 'Ipiranga Produtos de Petroleo S.A.'],
'.iselect' => ['type' => 'brand', 'info' => 'iSelect Ltd'],
'.itau' => ['type' => 'brand', 'info' => 'Itau Unibanco Holding S.A.'],
'.itv' => ['type' => 'brand', 'info' => 'ITV Services Limited'],
'.iveco' => ['type' => 'brand', 'info' => 'CNH Industrial N.V.'],
'.jaguar' => ['type' => 'brand', 'info' => 'Jaguar Land Rover Ltd'],
'.java' => ['type' => 'brand', 'info' => 'Oracle Corporation'],
'.jcb' => ['type' => 'brand', 'info' => 'JCB Co., Ltd.'],
'.jcp' => ['type' => 'brand', 'info' => 'JCP Media, Inc.'],
'.jeep' => ['type' => 'brand', 'info' => 'FCA US LLC (Jeep)'],
'.jpmorgan' => ['type' => 'brand', 'info' => 'JPMorgan Chase Bank, National Association'],
'.juniper' => ['type' => 'brand', 'info' => 'Juniper Networks, Inc.'],
'.kddi' => ['type' => 'brand', 'info' => 'KDDI Corporation'],
'.kerryhotels' => ['type' => 'brand', 'info' => 'Kerry Trading Co. Limited'],
'.kerrylogistics' => ['type' => 'brand', 'info' => 'Kerry Trading Co. Limited'],
'.kerryproperties' => ['type' => 'brand', 'info' => 'Kerry Trading Co. Limited'],
'.kfh' => ['type' => 'brand', 'info' => 'Kuwait Finance House'],
'.kia' => ['type' => 'brand', 'info' => 'Kia Motors Corporation'],
'.kindle' => ['type' => 'brand', 'info' => 'Amazon Registry Services, Inc.'],
'.komatsu' => ['type' => 'brand', 'info' => 'Komatsu Ltd.'],
'.kpmg' => ['type' => 'brand', 'info' => 'KPMG International Cooperative (KPMG International Genossenschaft)'],
'.kred' => ['type' => 'brand', 'info' => 'KredTLD'],
'.kuokgroup' => ['type' => 'brand', 'info' => 'Kerry Trading Co. Limited'],
'.lacaixa' => ['type' => 'brand', 'info' => 'Caixa d’Estalvis i Pensions de Barcelona'],
'.ladbrokes' => ['type' => 'brand', 'info' => 'Ladbrokes International PLC'],
'.lamborghini' => ['type' => 'brand', 'info' => 'Automobili Lamborghini S.p.A.'],
'.lancaster' => ['type' => 'brand', 'info' => 'Lancaster'],
'.lancia' => ['type' => 'brand', 'info' => 'Fiat Chrysler Automobiles N.V. (Lancia)'],
'.lancome' => ['type' => 'brand', 'info' => 'L\'Oréal'],
'.landrover' => ['type' => 'brand', 'info' => 'Jaguar Land Rover Ltd'],
'.lanxess' => ['type' => 'brand', 'info' => 'Lanxess Corporation'],
'.lasalle' => ['type' => 'brand', 'info' => 'Jones Lang LaSalle Incorporated'],
'.latrobe' => ['type' => 'brand', 'info' => 'La Trobe University'],
'.lds' => ['type' => 'brand', 'info' => 'The Church of Jesus Christ of Latter-day Saints (LDS Church)[203]'],
'.lego' => ['type' => 'brand', 'info' => 'LEGO Juris A/S'],
'.liaison' => ['type' => 'brand', 'info' => 'Liaison Technologies, Incorporated'],
'.lexus' => ['type' => 'brand', 'info' => 'Toyota Motor Corporation (Lexus)'],
'.lidl' => ['type' => 'brand', 'info' => 'Schwarz Domains und Services GmbH & Co. KG'],
'.lifestyle' => ['type' => 'brand', 'info' => 'Lifestyle Domain Holdings, Inc.'],
'.lilly' => ['type' => 'brand', 'info' => 'Eli Lilly and Company'],
'.lincoln' => ['type' => 'brand', 'info' => 'Ford Motor Company (Lincoln)'],
'.linde' => ['type' => 'brand', 'info' => 'Linde Aktiengesellschaft'],
'.lipsy' => ['type' => 'brand', 'info' => 'Lipsy Ltd'],
'.lixil' => ['type' => 'brand', 'info' => 'LIXIL Group Corporation'],
'.locus' => ['type' => 'brand', 'info' => 'Locus Analytics LLC'],
'.lotte' => ['type' => 'brand', 'info' => 'Lotte Holdings Co., Ltd.'],
'.lpl' => ['type' => 'brand', 'info' => 'LPL Holdings, Inc.'],
'.lplfinancial' => ['type' => 'brand', 'info' => 'LPL Holdings, Inc.'],
'.lundbeck' => ['type' => 'brand', 'info' => 'H. Lundbeck A/S'],
'.lupin' => ['type' => 'brand', 'info' => 'Lupin Limited'],
'.macys' => ['type' => 'brand', 'info' => 'Macy\'s, Inc.'],
'.maif' => ['type' => 'brand', 'info' => 'Mutuelle Assurance Instituteur France (MAIF)'],
'.man' => ['type' => 'brand', 'info' => 'MAN SE'],
'.mango' => ['type' => 'brand', 'info' => 'MANGO'],
'.marriott' => ['type' => 'brand', 'info' => 'Marriott Worldwide Corporation'],
'.maserati' => ['type' => 'brand', 'info' => 'Fiat Chrysler Automobiles N.V. (Maserati)'],
'.mattel' => ['type' => 'brand', 'info' => 'Mattel Sites, Inc.'],
'.mckinsey' => ['type' => 'brand', 'info' => 'McKinsey Holdings, Inc.'],
'.metlife' => ['type' => 'brand', 'info' => 'MetLife Services and Solutions, LLC'],
'.microsoft' => ['type' => 'brand', 'info' => 'Microsoft Corporation'],
'.mini' => ['type' => 'brand', 'info' => 'BMW (Mini)'],
'.mit' => ['type' => 'brand', 'info' => 'Massachusetts Institute of Technology'],
'.mitsubishi' => ['type' => 'brand', 'info' => 'Mitsubishi Corporation'],
'.mlb' => ['type' => 'brand', 'info' => 'MLB Advanced Media DH, LLC'],
'.mma' => ['type' => 'brand', 'info' => 'MMA IARD'],
'.monash' => ['type' => 'brand', 'info' => 'Monash University'],
'.mormon' => ['type' => 'brand', 'info' => 'The Church of Jesus Christ of Latter-day Saints (LDS Church)[203]'],
'.moto' => ['type' => 'brand', 'info' => 'Motorola Trademark Holdings, LLC'],
'.movistar' => ['type' => 'brand', 'info' => 'Telefónica S.A.'],
'.msd' => ['type' => 'brand', 'info' => 'MSD Registry Holdings, Inc.'],
'.mtn' => ['type' => 'brand', 'info' => 'MTN Dubai Limited'],
'.mtr' => ['type' => 'brand', 'info' => 'MTR Corporation Limited'],
'.mutual' => ['type' => 'brand', 'info' => 'Northwestern Mutual MU TLD Registry, LLC'],
'.nadex' => ['type' => 'brand', 'info' => 'Nadex Domains, Inc'],
'.nationwide' => ['type' => 'brand', 'info' => 'Nationwide Mutual Insurance Company'],
'.natura' => ['type' => 'brand', 'info' => 'Natura Cosméticos S.A.'],
'.nba' => ['type' => 'brand', 'info' => 'NBA Registry, LLC'],
'.nec' => ['type' => 'brand', 'info' => 'NEC Corporation'],
'.netflix' => ['type' => 'brand', 'info' => 'Netflix, Inc.'],
'.neustar' => ['type' => 'brand', 'info' => 'Neustar'],
'.newholland' => ['type' => 'brand', 'info' => 'CNH Industrial N.V.'],
'.nexus' => ['type' => 'brand', 'info' => 'Google (Google Nexus)'],
'.nfl' => ['type' => 'brand', 'info' => 'NFL Reg Ops LLC'],
'.nhk' => ['type' => 'brand', 'info' => 'NHK'],
'.nico' => ['type' => 'brand', 'info' => 'Dwango Co., Ltd. (Niconico)'],
'.nike' => ['type' => 'brand', 'info' => 'Nike, Inc.'],
'.nikon' => ['type' => 'brand', 'info' => 'Nikon Corporation'],
'.nissan' => ['type' => 'brand', 'info' => 'Nissan Motor Co., Ltd.'],
'.nissay' => ['type' => 'brand', 'info' => 'Nippon Life Insurance Company'],
'.nokia' => ['type' => 'brand', 'info' => 'Nokia Corporation'],
'.northwesternmutual' => ['type' => 'brand', 'info' => 'Northwestern Mutual Registry, LLC'],
'.norton' => ['type' => 'brand', 'info' => 'Symantec Corporation'],
'.nra' => ['type' => 'brand', 'info' => 'National Rifle Association'],
'.ntt' => ['type' => 'brand', 'info' => 'Nippon Telegraph And Telephone Corporation'],
'.obi' => ['type' => 'brand', 'info' => 'OBI Group Holding SE & Co. KGaA'],
'.office' => ['type' => 'brand', 'info' => 'Microsoft Corporation'],
'.omega' => ['type' => 'brand', 'info' => 'The Swatch Group Ltd'],
'.oracle' => ['type' => 'brand', 'info' => 'Oracle Corporation'],
'.orange' => ['type' => 'brand', 'info' => 'Orange Brand Services Limited'],
'.otsuka' => ['type' => 'brand', 'info' => 'Otsuka Holdings'],
'.ovh' => ['type' => 'brand', 'info' => 'OVH'],
'.panasonic' => ['type' => 'brand', 'info' => 'Panasonic Corporation'],
'.pccw' => ['type' => 'brand', 'info' => 'PCCW Enterprises Limited'],
'.pfizer' => ['type' => 'brand', 'info' => 'Pfizer Inc.'],
'.philips' => ['type' => 'brand', 'info' => 'Koninklijke Philips N.V.'],
'.piaget' => ['type' => 'brand', 'info' => 'Piaget SA'],
'.pictet' => ['type' => 'brand', 'info' => 'Pictet Europe S.A.'],
'.ping' => ['type' => 'brand', 'info' => 'Ping Registry Provider, Inc.'],
'.pioneer' => ['type' => 'brand', 'info' => 'Pioneer Corporation'],
'.play' => ['type' => 'brand', 'info' => 'Charleston Road Registry Inc. (Google)'],
'.playstation' => ['type' => 'brand', 'info' => 'Sony Computer Entertainment Inc.'],
'.pohl' => ['type' => 'brand', 'info' => 'Deutsche Vermögensberatung Aktiengesellschaft (founder Reinfried Pohl)'],
'.politie' => ['type' => 'brand', 'info' => 'Politie Nederland'],
'.praxi' => ['type' => 'brand', 'info' => 'Praxi'],
'.prod' => ['type' => 'brand', 'info' => 'Google (products)'],
'.progressive' => ['type' => 'brand', 'info' => 'Progressive Casualty Insurance Company'],
'.pru' => ['type' => 'brand', 'info' => 'Prudential Financial, Inc.'],
'.prudential' => ['type' => 'brand', 'info' => 'Prudential Financial, Inc.'],
'.pwc' => ['type' => 'brand', 'info' => 'PwC'],
'.quest' => ['type' => 'brand', 'info' => 'Quest ION Limited'],
'.qvc' => ['type' => 'brand', 'info' => 'QVC, Inc.'],
'.redstone' => ['type' => 'brand', 'info' => 'Redstone Haute Couture Co., Ltd.'],
'.reliance' => ['type' => 'brand', 'info' => 'Reliance Industries Limited'],
'.rexroth' => ['type' => 'brand', 'info' => 'Robert Bosch GmbH'],
'.ricoh' => ['type' => 'brand', 'info' => 'Ricoh Company, Ltd.'],
'.rmit' => ['type' => 'brand', 'info' => 'Royal Melbourne Institute of Technology'],
'.rocher' => ['type' => 'brand', 'info' => 'Ferrero Trading Lux S.A.'],
'.rogers' => ['type' => 'brand', 'info' => 'Rogers Communications Canada Inc.'],
'.rwe' => ['type' => 'brand', 'info' => 'RWE AG'],
'.safety' => ['type' => 'brand', 'info' => 'Safety Registry Services, LLC.'],
'.sakura' => ['type' => 'brand', 'info' => 'SAKURA Internet Inc.'],
'.samsung' => ['type' => 'brand', 'info' => 'SAMSUNG SDS CO., LTD'],
'.sandvik' => ['type' => 'brand', 'info' => 'Sandvik AB'],
'.sandvikcoromant' => ['type' => 'brand', 'info' => 'Sandvik Coromant'],
'.sanofi' => ['type' => 'brand', 'info' => 'Sanofi'],
'.sap' => ['type' => 'brand', 'info' => 'SAP SE'],
'.saxo' => ['type' => 'brand', 'info' => 'Saxo Bank A/S'],
'.sbi' => ['type' => 'brand', 'info' => 'State Bank of India'],
'.sbs' => ['type' => 'brand', 'info' => 'Special Broadcasting Service Corporation'],
'.sca' => ['type' => 'brand', 'info' => 'Svenska Cellulosa Aktiebolaget'],
'.scb' => ['type' => 'brand', 'info' => 'Siam Commercial Bank'],
'.schaeffler' => ['type' => 'brand', 'info' => 'Schaeffler Technologies AG & Co. KG'],
'.schmidt' => ['type' => 'brand', 'info' => 'Société Alsacienne de Meubles (Cuisines Schmidt)'],
'.schwarz' => ['type' => 'brand', 'info' => 'Schwarz Domains und Services GmbH & Co. KG'],
'.scjohnson' => ['type' => 'brand', 'info' => 'Johnson Shareholdings, Inc.'],
'.scor' => ['type' => 'brand', 'info' => 'SCOR SE'],
'.seat' => ['type' => 'brand', 'info' => 'SEAT, S.A. (Sociedad Unipersonal)'],
'.sener' => ['type' => 'brand', 'info' => 'Sener Ingeniería y Sistemas, S.A.'],
'.ses' => ['type' => 'brand', 'info' => 'SES'],
'.sew' => ['type' => 'brand', 'info' => 'SEW-EURODRIVE GmbH & Co KG'],
'.seven' => ['type' => 'brand', 'info' => 'Seven West Media Ltd'],
'.sfr' => ['type' => 'brand', 'info' => 'Societe Francaise du Radiotelephone - SFR'],
'.seek' => ['type' => 'brand', 'info' => 'Seek Limited'],
'.shangrila' => ['type' => 'brand', 'info' => 'Shangri‐La International Hotel Management Limited'],
'.sharp' => ['type' => 'brand', 'info' => 'Sharp Corporation'],
'.shaw' => ['type' => 'brand', 'info' => 'Shaw Cablesystems G.P.'],
'.shell' => ['type' => 'brand', 'info' => 'Shell Information Technology International Inc'],
'.shriram' => ['type' => 'brand', 'info' => 'Shriram Capital Ltd.'],
'.sina' => ['type' => 'brand', 'info' => 'Sina Corporation'],
'.sky' => ['type' => 'brand', 'info' => 'Sky plc'],
'.skype' => ['type' => 'brand', 'info' => 'Microsoft Corporation'],
'.smart' => ['type' => 'brand', 'info' => 'Smart Communications, Inc. (SMART)'],
'.sncf' => ['type' => 'brand', 'info' => 'SNCF (Société Nationale des Chemins de fer Français)'],
'.softbank' => ['type' => 'brand', 'info' => 'SoftBank Group Corp.'],
'.sohu' => ['type' => 'brand', 'info' => 'Sohu'],
'.sony' => ['type' => 'brand', 'info' => 'Sony Corporation'],
'.spiegel' => ['type' => 'brand', 'info' => 'Spiegel-Verlag'],
'.stada' => ['type' => 'brand', 'info' => 'STADA Arzneimittel AG'],
'.staples' => ['type' => 'brand', 'info' => 'Staples, Inc.'],
'.star' => ['type' => 'brand', 'info' => 'Star India Private Limited'],
'.starhub' => ['type' => 'brand', 'info' => 'StarHub Limited'],
'.statebank' => ['type' => 'brand', 'info' => 'State Bank of India'],
'.statefarm' => ['type' => 'brand', 'info' => 'State Farm Mutual Automobile Insurance Company'],
'.statoil' => ['type' => 'brand', 'info' => 'Statoil ASA'],
'.stc' => ['type' => 'brand', 'info' => 'Saudi Telecom Company'],
'.stcgroup' => ['type' => 'brand', 'info' => 'Saudi Telecom Company'],
'.suzuki' => ['type' => 'brand', 'info' => 'Suzuki Motor Corporation'],
'.swatch' => ['type' => 'brand', 'info' => 'The Swatch Group Ltd'],
'.swiftcover' => ['type' => 'brand', 'info' => 'Swiftcover Insurance Services Limited'],
'.symantec' => ['type' => 'brand', 'info' => 'Symantec Corporation'],
'.taobao' => ['type' => 'brand', 'info' => 'Alibaba Group Holding Limited'],
'.target' => ['type' => 'brand', 'info' => 'Target Domain Holdings, LLC'],
'.tatamotors' => ['type' => 'brand', 'info' => 'Tata Motors Ltd'],
'.tdk' => ['type' => 'brand', 'info' => 'TDK Corporation'],
'.telecity' => ['type' => 'brand', 'info' => 'TelecityGroup International Limited'],
'.telefonica' => ['type' => 'brand', 'info' => 'Telefónica S.A.'],
'.temasek' => ['type' => 'brand', 'info' => 'Temasek Holdings (Private) Limited'],
'.teva' => ['type' => 'brand', 'info' => 'Teva Pharmaceutical Industries Limited'],
'.tiffany' => ['type' => 'brand', 'info' => 'Tiffany and Company'],
'.tjx' => ['type' => 'brand', 'info' => 'The TJX Companies, Inc.'],
'.toray' => ['type' => 'brand', 'info' => 'Toray Industries, Inc.'],
'.toshiba' => ['type' => 'brand', 'info' => 'TOSHIBA Corporation'],
'.total' => ['type' => 'brand', 'info' => 'Total SA'],
'.toyota' => ['type' => 'brand', 'info' => 'Toyota Motor Corporation'],
'.travelchannel' => ['type' => 'brand', 'info' => 'Lifestyle Domain Holdings, Inc.'],
'.travelers' => ['type' => 'brand', 'info' => 'Travelers TLD, LLC'],
'.tui' => ['type' => 'brand', 'info' => 'TUI AG'],
'.tvs' => ['type' => 'brand', 'info' => 'T V Sundram Iyengar & Sons Private Limited'],
'.ubs' => ['type' => 'brand', 'info' => 'UBS AG'],
'.unicom' => ['type' => 'brand', 'info' => 'China United Network Communications Corporation Limited'],
'.uol' => ['type' => 'brand', 'info' => 'Universo Online'],
'.ups' => ['type' => 'brand', 'info' => 'UPS Market Driver, Inc.'],
'.vanguard' => ['type' => 'brand', 'info' => 'The Vanguard Group, Inc.'],
'.verisign' => ['type' => 'brand', 'info' => 'VeriSign, Inc.'],
'.vig' => ['type' => 'brand', 'info' => 'Vienna Insurance Group AG Wiener Versicherung Gruppe'],
'.viking' => ['type' => 'brand', 'info' => 'Viking River Cruises (Bermuda) Ltd.'],
'.virgin' => ['type' => 'brand', 'info' => 'Virgin Enterprises Limited'],
'.visa' => ['type' => 'brand', 'info' => 'Visa Worldwide Pte. Limited'],
'.vista' => ['type' => 'brand', 'info' => 'Vistaprint Limited'],
'.vistaprint' => ['type' => 'brand', 'info' => 'Vistaprint Limited'],
'.vivo' => ['type' => 'brand', 'info' => 'Telefónica Brasil S.A.'],
'.volkswagen' => ['type' => 'brand', 'info' => 'Volkswagen Group of America Inc.'],
'.volvo' => ['type' => 'brand', 'info' => 'Volvo Holding Sverige Aktiebolag'],
'.walmart' => ['type' => 'brand', 'info' => 'Walmart, Inc.'],
'.walter' => ['type' => 'brand', 'info' => 'Sandvik AB'],
'.weatherchannel' => ['type' => 'brand', 'info' => 'International Business Machines Corporation (The Weather Company)'],
'.weber' => ['type' => 'brand', 'info' => 'Saint-Gobain Weber SA'],
'.weir' => ['type' => 'brand', 'info' => 'Weir Group IP Limited'],
'.williamhill' => ['type' => 'brand', 'info' => 'William Hill'],
'.windows' => ['type' => 'brand', 'info' => 'Microsoft Corporation'],
'.wme' => ['type' => 'brand', 'info' => 'William Morris Endeavor Entertainment'],
'.wolterskluwer' => ['type' => 'brand', 'info' => 'Wolters Kluwer N.V.'],
'.woodside' => ['type' => 'brand', 'info' => 'Woodside Petroleum Limited'],
'.wtc' => ['type' => 'brand', 'info' => 'World Trade Centers Association'],
'.xbox' => ['type' => 'brand', 'info' => 'Microsoft Corporation'],
'.xerox' => ['type' => 'brand', 'info' => 'Xerox DNHC LLC'],
'.xfinity' => ['type' => 'brand', 'info' => 'Comcast IP Holdings I, LLC'],
'.yahoo' => ['type' => 'brand', 'info' => 'Yahoo! Domain Services Inc.'],
'.yamaxun' => ['type' => 'brand', 'info' => 'Amazon Registry Services, Inc.'],
'.yandex' => ['type' => 'brand', 'info' => 'Yandex'],
'.yodobashi' => ['type' => 'brand', 'info' => 'YODOBASHI CAMERA CO., LTD.'],
'.youtube' => ['type' => 'brand', 'info' => 'Google (YouTube)'],
'.zappos' => ['type' => 'brand', 'info' => 'Amazon Registry Services, Inc.'],
'.zara' => ['type' => 'brand', 'info' => 'Industria de Diseño Textil, S.A. (INDITEX, S.A.)'],
'.zip' => ['type' => 'brand', 'info' => 'Charleston Road Registry Inc. (Google)'],
'.zippo' => ['type' => 'brand', 'info' => 'Zadco Company'],
'.example' => ['type' => 'special', 'info' => 'Not installed as a domain name, but usable in text as an example. example.com, example.net and example.org are also reserved for this purpose but are active sites.'],
'.invalid' => ['type' => 'special', 'info' => 'Not installed as a domain name, but usable in testing as a domain which wouldn\'t work.'],
'.local' => ['type' => 'special', 'info' => 'Local network'],
'.localhost' => ['type' => 'special', 'info' => 'Points back to own computer'],
'.onion' => ['type' => 'special', 'info' => 'Connection to the Tor network'],
'.test' => ['type' => 'special', 'info' => 'Meant for testing DNS software'],

]);
